### ISSUE TITLE
positions and orders by lot number

### ISSUE THREAD

**Issue by hz2018tv** [alpacahq/alpaca-trade-api-python#106]
How to manage positions and orders by lot number? Have not found it by web gui and APIs

Guess not all algo go by all-or-none type of transactions. 

Thanks

**Comment by ttt733** [comment]
Hi, could you please clarify what you're looking for in a lot number? Our API doesn't really have a concept of that; the positions we return are aggregated.

**Comment by hz2018tv** [comment]
say you bought 1 msft@41, then bought another 1@39, when reporting position, we see 1@41 and 1@39, instead of 2@40.

**Comment by Jacyle** [comment]
I have this same question. It's very important for tax purposes. How am I supposed to report my trading activity otherwise?

Perhaps you could develop the capability using the 'client_order_id'?

**Comment by ttt733** [comment]
The desire for this is on our radar, but it's currently not feasible with our backend. If you have questions about particular positions or need help managing the tax information, please contact our brokerage staff here: https://support.alpaca.markets/hc/en-us/requests/new
