### ISSUE TITLE
get_barset() still ignores start and end date

### ISSUE THREAD

**Issue by edwardyu** [alpacahq/alpaca-trade-api-python#109]
I've looked through #66 and the advice doesn't work.

```
bars = api.get_barset(['AAPL'], '1D', limit=100, start=pd.Timestamp('2010-01-01', tz='America/New_York').isoformat())
print(bars.df)
```

```
                               AAPL                                        
                               open      high       low     close    volume
time                                                                       
2019-03-27 00:00:00-04:00  188.7500  189.7600  186.5500  188.4700  26586290
2019-03-28 00:00:00-04:00  188.9500  189.5590  187.5300  188.7100  19309376
2019-03-29 00:00:00-04:00  189.9900  190.0800  188.5400  189.9400  18489986
2019-04-01 00:00:00-04:00  191.6400  191.6800  188.3800  191.2400  12098014
2019-04-02 00:00:00-04:00  191.0900  194.4600  191.0500  194.0400  19797454
2019-04-03 00:00:00-04:00  193.2500  196.5000  193.1500  195.3500  19793141
2019-04-04 00:00:00-04:00  194.7900  196.3700  193.1400  195.7200  17091108
2019-04-05 00:00:00-04:00  196.4500  197.1000  195.9300  196.9700  15842943
2019-04-08 00:00:00-04:00  196.4200  200.2300  196.3400  200.0800  23231403
2019-04-09 00:00:00-04:00  200.3200  202.8500  199.2300  199.5000  32840959
2019-04-10 00:00:00-04:00  198.6800  200.7400  198.1800  200.6600  19861942
2019-04-11 00:00:00-04:00  200.8500  201.0000  198.4431  198.9500  17931789
2019-04-12 00:00:00-04:00  199.2000  200.1400  196.2100  198.8800  24667735
2019-04-15 00:00:00-04:00  198.5800  199.8500  198.0100  199.2300  14551176
2019-04-16 00:00:00-04:00  199.4600  201.3700  198.5600  199.2500  24002891
2019-04-17 00:00:00-04:00  199.5400  203.3800  198.6100  203.1200  27366117
2019-04-18 00:00:00-04:00  203.1200  204.1500  202.5200  203.8600  21928367
2019-04-22 00:00:00-04:00  202.8300  204.9400  202.3400  204.6400  13720923
2019-04-23 00:00:00-04:00  204.4300  207.7500  203.9000  207.5100  19401417
2019-04-24 00:00:00-04:00  207.3600  208.4800  207.0500  207.1800  14914939
2019-04-25 00:00:00-04:00  206.8300  207.7600  205.1200  205.2400  15908807
2019-04-26 00:00:00-04:00  204.9000  205.0000  202.1200  204.2900  16315669
2019-04-29 00:00:00-04:00  204.4000  205.9700  203.8600  204.6100  19641066
2019-04-30 00:00:00-04:00  203.0600  203.4000  199.1100  200.5700  35362106
2019-05-01 00:00:00-04:00  209.8800  215.3100  209.2300  210.5200  57751414
2019-05-02 00:00:00-04:00  209.8400  212.6500  208.1300  209.1700  29014844
2019-05-03 00:00:00-04:00  210.7400  211.8400  210.2300  211.7800  17987793
2019-05-06 00:00:00-04:00  204.2900  208.8400  203.5000  208.6000  28949691
2019-05-07 00:00:00-04:00  205.8800  207.4175  200.8250  202.8600  34328425
2019-05-08 00:00:00-04:00  201.9000  205.3400  201.7500  202.9000  22729670
...                             ...       ...       ...       ...       ...
```

**Comment by bojanglebells** [comment]
Hi there, 

I was having the same issue. I was able to fix it by appending '-04:00' to what pd.Timestamp().isoformat() returns. 

So: 
good_date = pd.Timestamp(<date to convert>).isoformat() + '-04:00'

It seems like the '-04:00' is important, as if it is not present or changed to something else, the .get_barset function seems to ignore the date entirely - even if formatted with .isoformat()

Hope that helps!

**Comment by edwardyu** [comment]
@bojanglebells thanks for your comment. I don't think this is the issue however, as `isoformat()` does include the timezone. 

```
start = pd.Timestamp('2010-01-01', tz='America/New_York').isoformat()
print(start)

>>>  2010-01-01T00:00:00-05:00
```

**Comment by bnicholl** [comment]
Is there a fix to this? I'm not sure how anyone is supposed to use Alpaca to backtests anything if we can't get historical tick data based on a specific timeframe.

**Comment by jholland1** [comment]
Same issue using Timestamp, but I did get it working by just entering strings in the precise format below.  Couldn't get it to work with the suggested fix for #66 or adding -04:00 to the pd.Timestamp().isoformat() output.
```
fts='2018-05-08T09:45:00-04:00'
tts = '2019-05-08T09:45:00-04:00'
aapl_daily = api.get_barset('AAPL', 'minute', start=fts, end=tts).df
print(aapl_daily)
```

**Comment by RDPEast** [comment]
Has anyone had any luck with this? As bnicholl points out above this is basically unusable if there is no fix.

**Comment by jeichenseerNRX** [comment]
It's definitely fussy. Here's an example that seems to work. 

```
def get_first_two_hours_minute_bars(symbol, timestamp):
    start = timestamp.replace(hour=9, minute=30).astimezone('GMT').isoformat()[:-6]+'Z'
    end = timestamp.replace(hour=11, minute=30).astimezone('GMT').isoformat()[:-6]+'Z'
    df = live_api.get_barset(symbol, '1Min', start=start, end=end).df
    return df

df = open_bars('AAPL', pandas.Timestamp('2019-09-10 00:00:00-0400', tz='America/New_York'))
print(df.head(), df.tail())
```

**Comment by mfigurski80** [comment]
@jeichenseerNRX fixed this issue for me: it's primarily about the api requiring that specific formatting, which timestamp.isoformat() doesn't actually provide. Api endpoint accepts `2019-01-01T00:00:00Z`, whereas isoformat generally returns something like this: `2020-02-08T04:28:33.287093`. Notably, these differ by the addition of milliseconds and the 'Z' at the end.

This is current cli get_barset:
```
 def get_barset(self,
                   symbols,
                   timeframe,
                   limit=None,
                   start=None,
                   end=None,
                   after=None,
                   until=None):
        '''Get BarSet(dict[str]->list[Bar])
        The parameter symbols can be either a comma-split string
        or a list of string. Each symbol becomes the key of
        the returned value.
        '''
        if not isinstance(symbols, str):
            symbols = ','.join(symbols)
        params = {
            'symbols': symbols,
        }
        if limit is not None:
            params['limit'] = limit
        if start is not None:
            params['start'] = start
        if end is not None:
            params['end'] = end
        if after is not None:
            params['after'] = after
        if until is not None:
            params['until'] = until
        resp = self.data_get('/bars/{}'.format(timeframe), params)
        return BarSet(resp)
```

Personally, I would like to see one or both pairs of these variables dedicated to accepting a pandas timestamp object that it would then manipulate into a string of its own liking. Would be less of a headache

**Comment by auwsom** [comment]
It looks to me like the API is working from newest backwards by default. So if you use the boilerplate from their API docs and add a start, it will not work. Only by either changing start to end, or having both as in jholland1's reply [above](https://github.com/alpacahq/alpaca-trade-api-python/issues/109#issuecomment-528493730) will it work. You also do need the isoformat(), but can use a simple date as in the OP, but not too far back, I think only a couple of years.
```
barset = api.get_barset('AAPL', 'day', limit=5, end=pandas.Timestamp('2019-01-01', tz='America/New_York').isoformat())
aapl_bars = barset['AAPL']
```

**Comment by bbeale** [comment]
I ran into this while trying to use the `until` parameter. 

After struggling for a bit, something like this works for me if using datetimes `until=dt.strftime('%Y-%m-%dT%H:%M:%S.%f-04:00')`. If not using datetimes, whatever other means to get the date into that format should work.

**Comment by mufniarz** [comment]
DataFrame code
```

import pandas as pd
df1 = api.get_barset('GE', '5Min', limit=10, start=None, end=None, after=None, until=None).df

df2 = api.get_barset('GE', '5Min', limit=10, start=None, end=None, after=None, until=df1.first_valid_index().isoformat()).df

df3 = api.get_barset('GE', '5Min', limit=10, start=None, end=None, after=None, until=df2.first_valid_index().isoformat()).df

frames = [df3, df2, df1]

result = pd.concat(frames)
result

```

Bars object
```

obj1 = api.get_barset('GE', '5Min', limit=10, start=None, end=None, after=None, until=None)

obj2 = api.get_barset('GE', '5Min', limit=10, start=None, end=None, after=None, until=obj1['GE'][0].t.isoformat())

obj3 = api.get_barset('GE', '5Min', limit=10, start=None, end=None, after=None, until=obj2['GE'][0].t.isoformat())

frames = [obj3['GE'], obj2['GE'], obj1['GE']]

result = []
for frame in frames:
    result.extend(frame) 
result

```
Works fine for me.

**Comment by riodda** [comment]
Thanks mufniarz, i made this little function inspired by your code, I hope somebody will find it usefoul

`def get_15Min_bars(_symbol,_number):
    _df=pd.DataFrame()
    _temp=pd.DataFrame()
    if _number<1000:
        _df = api.get_barset(_symbol, '15Min', limit=_number, start=None, end=None, after=None, until=None).df
    else:
        _num_cycles, _residual = divmod(_number, 1000)
        _df = api.get_barset(_symbol, '15Min', limit=_residual, start=None, end=None, after=None, until=None).df
        for i in range(1,_num_cycles+1):
            _temp = api.get_barset(_symbol, '15Min', limit=1000, start=None, end=None, after=None, until=_df.first_valid_index().isoformat()).df
            print(_df.first_valid_index().isoformat())
            _df= pd.concat([_temp,_df,])
    return _df`

**Comment by jabowery** [comment]
Wasted a day tracking this down till I found jholland1's nuclear flyswatter. Bad documentation.  Fix it.

**Comment by shlomikushchi** [comment]
Hi guys. 
this code snippet is an example on how to use the 
```python
import pandas as pd
NY = 'America/New_York'
start=pd.Timestamp('2020-08-01', tz=NY).isoformat()
end=pd.Timestamp('2020-08-30', tz=NY).isoformat()
print(api.get_barset(['AAPL', 'GOOG'], 'day', start=start, end=end).df)
```
also added it to the readme: https://github.com/alpacahq/alpaca-trade-api-python/pull/309
