### ISSUE TITLE
Websocket Error - Anyone else getting this?

### ISSUE THREAD

**Issue by CapitalZe** [alpacahq/alpaca-trade-api-python#112]
Several months back I installed alpaca, zipline, pylivetrader etc to test these platforms out and play around with them. After some trouble-shooting everything went well and it all worked as expected.

I've just come back and tried to reinstall (as I no longer have the original test installation) and now I am confronted with this error:
 `Collecting websockets>=8.0 (from alpaca-trade-api>=0.38->pylivetrader)
  ERROR: Could not find a version that satisfies the requirement websockets>=8.0 (from alpaca-trade-api>=0.38->pylivetrader) (from versions: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3, 3.4, 4.0, 4.0.1, 5.0, 5.0.1, 6.0, 7.0)
ERROR: No matching distribution found for websockets>=8.0 (from alpaca-trade-api>=0.38->pylivetrader)
`

I've spent as much time as I can trying to resolve it but am not able to make any progress on it.

For clarification:

- Host Machine Macbook
- VMware
- Guest OS = Ubuntu 16.04

I have changed nothing on this particular machine other than delete the original pylivetrader (etc) installation after I had finished several months back yet now this error is raised no matter which method I use to install pylivetrader, alpaca-trade-api, zipline, pipeline-live etc.

If anyone has any insight onto this I'd be particularly grateful.

**Comment by ttt733** [comment]
This is an issue with your Python version, as I mentioned in the pylivetrader issue. You need Python >= 3.6, as 3.5 is not supported by the new version of the websockets dependency.

**Comment by CapitalZe** [comment]
I had followed every step I could to ensure my venv was solely running python 3.6

BUt in the error codes there were clear python conflicts, as you stated.

In the end I solved it, amongst some other conflicts in my system with:

`sudo apt-get install python3.6-dev
`

I hope this helps someone else; it had me snagged for days.

**Comment by lqin1** [comment]
ERROR: Could not find a version that satisfies the requirement websockets>=8.0 (from alpaca-trade-api) (from versions: 1.0, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 3.3, 3.4, 4.0, 4.0.1, 5.0, 5.0.1, 6.0, 7.0)
ERROR: No matching distribution found for websockets>=8.0 (from alpaca-trade-api)

I got this error.
I am on ubuntu 16.04 with python 3.8.3

**Comment by shlomikushchi** [comment]
just installed it on ubuntu 16.04 with python 3.6.10

![image](https://user-images.githubusercontent.com/7924802/85847573-4e0fb200-b7b0-11ea-9b2e-b649f99196f9.png)

**Comment by shlomikushchi** [comment]
check the websockets pypi page:
https://pypi.org/project/websockets/#history

**Comment by Slow1** [comment]
I have the same error on a venv, using python 3.6 and can't install websockets 9.1.1 or >
