### ISSUE TITLE
Occasional request 404

### ISSUE THREAD

**Issue by NescienceSoftware** [alpacahq/alpaca-trade-api-python#116]
I had been running with no issues for the past couple weeks but starting this past monday on the rara occasion a 404 pops up when calling asset prices from polygon with the sandbox/ paper trading API

"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.polygon.io/v1/last/stocks/XLU?apiKey=PKH47JEKAPDBW0D74MAY"

Could this be a result of rate limitation or is it just simple 404 from polygon?

**Comment by CapitalZe** [comment]
I'm experiencing similar, as posted [here](https://github.com/alpacahq/pylivetrader/issues/125).

Any help would be much appreciated.

**Comment by CapitalZe** [comment]
A fresh install solved it for me.

**Comment by NescienceSoftware** [comment]
I implemented a small rate limitation + added try loops to the affected portions. The 404 was only occasional so I am not sure if it still happens with the rate limitation or it is just worked around by the try loop.

**Comment by umitanuki** [comment]
I will relay it to Polygon.
