### ISSUE TITLE
Depreciation of some V1 endpoints

### ISSUE THREAD

**Issue by keramtalb** [alpacahq/alpaca-trade-api-python#123]
Polygon has announced retiring some of the tick end points still used in this library on Jan 1, 2020 - https://polygon.io/blog/action-required-v1-tick-api-will-be-deprecated-on-01-01-2020/.

Is there any work underway to address this?

**Comment by ttt733** [comment]
We have not done any deprecation warnings in the past, but I will see about adding a warning in a future release. I just opened a draft PR allowing use of the V2 endpoints; once I've been able to confirm something about the response from Polygon I should be able to add the replacements.
