### ISSUE TITLE
Event loop is already running and websocket question

### ISSUE THREAD

**Issue by wjg59701** [alpacahq/alpaca-trade-api-python#126]
Hello, I am trying to run the code example that trades on slight moves in the bid/ask spread, posted here on github.

Using alpaca_trade_api StreamConn object, I get a runtime error "This event loop is already running"

I have also tried directly connecting to the alpaca api just using the websockets library but I need a wss: url and alpaca only provides the https .../stream address.

can someone help and/or point me to a good source/tutorial for establishing multiple websockets and asyncio?

I have a polygon account for streaming data and I can simply connect to that as a websocket but I want to use the alpaca stream 'trade_updates' as well.

**Comment by ttt733** [comment]
The API URL for a direct connection is the same, just with https:// replaced with wss://. I.e., `wss://paper-api.alpaca.markets` or `wss://api.alpaca.markets`. So a connection might look like:
```
conn = tradeapi.StreamConn(
        'X',
        'X',
        'wss://paper-api.alpaca.markets'
    )

@conn.on(r'trade_updates')
async def on_trade_update(conn, channel, data):
    pass

conn.run(['trade_updates'])
```

Replace the Xs with your API keys and pass with whatever code you want to handle them. If you have trouble connecting in this way, please reopen the issue and let us know more - copy the full error output if possible.

**Comment by GitHubEmploy** [comment]
Hello, I tried running this and it started spamming 'ERROR:root:error while consuming ws messages: server rejected WebSocket connection: HTTP 429', and every 3 it said, 'ERROR:root:error while consuming ws messages: Error while connecting to wss://data.alpaca.markets/stream:your connection is rejected while another connection is open under the same account'. So now I am trying to figure out how to terminate that connection. This happened when I clicked disconnect instead of terminate.

**Comment by shlomikushchi** [comment]
Hi, what do you mean "clicked disconnect" where did you click?
the errors you see caused by the websocket client trying to reconnect to the server

**Comment by GitHubEmploy** [comment]
Ok, let me explain in more detail. I use a IDE called PyCharm, and when you stop a program in PyCharm you have 2 options. You can either disconnect from the program, or terminate the program. The main difference is disconnection is where it is still running on your computer, but PyCharm is no longer hosting the program, and terminate is where you stop the program.

**Comment by shlomikushchi** [comment]
so you need to kill the python process running this code. you can't have more than one connection to the websocket, this is why you get this error.

**Comment by nickvertucci** [comment]
@ttt733 Are you able to assist with the momentum template? I just ran into this same error.
