### ISSUE TITLE
getPercentChanges calls the get_barset for minute length? but the comment says for day length

### ISSUE THREAD

**Issue by aleel1597** [alpacahq/alpaca-trade-api-python#127]
I was wondering why the getPercentChanges calls bars = self.alpaca.get_barset(stock[0], 'minute', length) on line 312 for the 'minute' as the second argument when the comment says it wants the percent change over past 10 days?

**Comment by aleel1597** [comment]
this was for the example code in long-short.py

**Comment by ttt733** [comment]
The comment in the example has been updated, thank you for pointing it out.
