### ISSUE TITLE
cancel_order not working

### ISSUE THREAD

**Issue by PrashantJalan** [alpacahq/alpaca-trade-api-python#135]
The cancel_order call in the REST api that calls Alpaca seem to execute fine but the order is still open. I tested this outside regular trading hours. Not sure if it works during normal trading hours. Regardless, it should throw an exception if the order was not cancelled.

**Comment by umitanuki** [comment]
The order cancelation is asynchronous and depends on the venue's action to reflect the order has been canceled or not which is indicated in the status. So, it is not realistic to throw exception synchronously. That said, from API caller perspective we understand it's hard to know if cancel is in progress, so we are planning to add more information in order entity for better visibility.

**Comment by PrashantJalan** [comment]
Thank you for the clarification. So is it possible that the cancel order I
sent on Saturday will be executed on Monday?

**Comment by ttt733** [comment]
That's correct. We mark the order as canceled at Alpaca, and at the next possible opportunity, we send the cancellation request to the market. We've been discussing ways to make this more obvious in the cancel endpoint's response.
