### ISSUE TITLE
New orders/positions not showing on UI

### ISSUE THREAD

**Issue by CacheMoneyPlaya** [alpacahq/alpaca-trade-api-python#141]
I have noticed that any order I place does not show up on the main dashboard when using papertrades.

Say I use the payload:
    ```api.submit_order(symbol='AAPL',
    qty=1,
    side='buy',
    type='market',
    time_in_force='gtc')```

The following is returned to me indicating an order was placed:
```Order({   'asset_class': 'us_equity',
    'asset_id': 'b0b6dd9d-8b9b-48a9-ba46-b9d54906e415',
    'canceled_at': None,
    'client_order_id': '42dc792f-753c-4799-a7c7-d4673ba8d661',
    'created_at': '2020-01-24T20:22:57.302849Z',
    'expired_at': None,
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'id': '5a263c99-b09d-425c-b060-a0df7b0cec60',
    'legs': None,
    'limit_price': None,
    'order_type': 'market',
    'qty': '1',
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': 'buy',
    'status': 'new',
    'stop_price': None,
    'submitted_at': '2020-01-24T20:22:57.220258Z',
    'symbol': 'AAPL',
    'time_in_force': 'gtc',
    'type': 'market',
    'updated_at': '2020-01-24T20:22:57.307831Z'})```

However this never shows within the UI that the order has been placed. My credentials are correct as I can place orders manually via the dashboard and then send a request to get my open orders/positions from my bot.

Using python 3+

**Comment by Elad-Levi** [comment]
How was the case solved? facing same here..

**Comment by CacheMoneyPlaya** [comment]
> How was the case solved? facing same here..

Hey sorry for late reply. I can't fully remember why but it was something to do with my params. I have added a snippet of my order exexution below as this config works for me.

api.api.submit_order(t, sell_qty, "sell", "market", "day")

**Comment by juanfp900** [comment]
Im having the same issue. 
I do self.api.submit_order(symbol, qty, side, type, time_in_force) 
but it doesn't show my order on the alpca website paper trading dashboard.
 I dont know why..

**Comment by CacheMoneyPlaya** [comment]
> Im having the same issue.
> I do self.api.submit_order(symbol, qty, side, type, time_in_force)
> but it doesn't show my order on the alpca website paper trading dashboard.
> I dont know why..
> Anyone have suggestions?

Try using this exact line hard coded (I use api as my alpaca sdk instatiation, obvs use what you instantiated it as):

` api.submit_order("AAPL", "1", "buy", "market", "day")` , 

if that doesnt work it has to be something to do with your keys. :/

**Comment by DanielWestrich** [comment]
I found that resetting my API keys sometimes works, but not always.

**Comment by dc500** [comment]
I have that. It still doesn't work for me. _

`elif delta < 0:
                sell_qty = abs(delta)
                if self.position > 0:
                    sell_qty = min(abs(self.position), sell_qty)
                print(f'Selling {sell_qty} shares.')
                self.current_order = self.api.submit_order(
                    self.symbol, sell_qty, 'sell',
                    'limit', 'day', self.last_price
                )
        except Exception as e:
            print(e)`

**Comment by pongnguy** [comment]
I am facing something similar.  It does not show up on Chrome.  However it shows up when I view it from my phone.
