### ISSUE TITLE
Getting error "failed to calculate balances" on submit_order()

### ISSUE THREAD

**Issue by PrashantJalan** [alpacahq/alpaca-trade-api-python#142]
Hi, I'm receiving a new type of error while trying to place a buy order (using the Python Alpaca API). 99% it runs without any error, but sometimes I'm getting a new type of error with the error message "failed to calculate balances". I can't find anything obviously wrong in my implementation. Could you please help explain this error?

**Comment by umitanuki** [comment]
The error seems that it most likely comes from the backend service side, not your code.

**Comment by ttt733** [comment]
There were some service issues last week that may be related to this. If you encounter the issue again, please post a log of the error's output and reopen this ticket.
