### ISSUE TITLE
Intraday barsets not available on Alpaca Data API prior to 2017-11-21

### ISSUE THREAD

**Issue by t-shah** [alpacahq/alpaca-trade-api-python#143]
For example, running
`api.get_barset('AAPL', 'minute', limit=1, end='2017-11-21T10:00:00-05:00')`
returns
`{'AAPL': []}`

But, running
`api.get_barset('AAPL', 'minute', limit=1, end='2017-11-22T10:00:00-05:00')`
returns
`{'AAPL': [Bar({'c': 173.46, 'h': 173.46, 'l': 173.31, 'o': 173.36, 't': 1511362800, 'v': 2111})]}`
as expected.

This behavior is consistent across various stocks. I've tried other dates earlier than 11/21/2017 with unsuccessful results, and I've tried many other dates from 11/22/2017 to today with success.

Oddly, daily bars do seem to be available, just not intraday...

**Comment by ttt733** [comment]
This is true - the history of some data through that endpoint is limited. If you need older data, you'll need to use the Polygon data source instead. Theirs goes back much farther.

**Comment by t-shah** [comment]
Thanks for the feedback
