### ISSUE TITLE
Install fails in python notebook

### ISSUE THREAD

**Issue by 7ruth** [alpacahq/alpaca-trade-api-python#147]
When I try to install this package in a python notebook the install fails.

In python notebook I run:
```
!pip install alpaca_trade_api

import alpaca_trade_api as ata

```

I get:
![image](https://user-images.githubusercontent.com/10719152/73940917-4cedef00-48ba-11ea-8a3b-a434a6fba263.png)

**Comment by thomaswadeculbertson** [comment]
I have the exact same problem. Last night everything worked fine. This morning it gives the same error you are getting. I am using Google colab jupyter notebook.  I noted that there was an update to the alpaca trade api between last night and this morning.  (02/04/2020) to (02/05/2020) 

Are you using python jupyter notebook?
What platform are you running on?

    ImportError                               Traceback (most recent call last)
    <ipython-input-24-6d9fd838d3de> in <module>()
    ----> 1 import alpaca_trade_api as tradeapi
          2 
          3 api = tradeapi.REST()
          4 account = api.get_account()
          5 account.status

    1 frames
    /usr/local/lib/python3.6/dist-packages/alpaca_trade_api/__init__.py in <module>()
    ----> 1 from .rest import REST  # noqa
          2 from .stream2 import StreamConn  # noqa
          3 
          4 __version__ = '0.43'

    /usr/local/lib/python3.6/dist-packages/alpaca_trade_api/rest.py in <module>()
         16 )
         17 from . import polygon
    ---> 18 from . import alpha_vantage
         19 
         20 logger = logging.getLogger(__name__)

    ImportError: cannot import name 'alpha_vantage'

**Comment by ttt733** [comment]
Sorry about this, guys - we had an external PR that forgot to add the new package to setup.py and I didn't catch it. A fix is being deployed to PyPi now.
