### ISSUE TITLE
Error / Bug: submit_order() got an unexpected keyword argument 'order_class'

### ISSUE THREAD

**Issue by powderblock** [alpacahq/alpaca-trade-api-python#153]
When using the provided example:

```
api = tradeapi.REST(API_KEY, API_SECRET, APCA_API_BASE_URL, api_version='v2') # or use ENV Vars shown below

api.submit_order(
    symbol='SPY',
    side='buy',
    type='market',
    qty='100',
    time_in_force='day',
    order_class='bracket',
    take_profit=dict(
        limit_price='305.0',
    ),
    stop_loss=dict(
        stop_price='295.5',
        limit_price='295.5',
    )
)
```

I get the following error: 

`TypeError: submit_order() got an unexpected keyword argument 'order_class'`

Could this be due to the version of API I have installed? And or the fact that I am calling api_version v2?

Any help appreciated.

Thanks in advance.

**Comment by umitanuki** [comment]
It must be the SDK version. Could you try upgrade it to the latest one?

**Comment by powderblock** [comment]
**SOLVED:**  Upgrading version fixed the issue. Thank you!!!
