### ISSUE TITLE
StreamConn - Polygon credentials error when trying to use it for bars updates in paper trading

### ISSUE THREAD

**Issue by esoli2** [alpacahq/alpaca-trade-api-python#155]
Trying to set up a stream for stock price updates for paper trading. However, every time I get: 

> ValueError: Invalid Polygon credentials, Failed to authenticate: {'ev': 'status', 'status': 'auth_failed', 'message': 'authentication failed'}

Amongst many other variations, this is the code that I have been trying to use: 

```
import alpaca_trade_api as tradeapi

conn = tradeapi.StreamConn(
    'PKGPXJAP36G35ZUJUYRW',
    'QmGX9UOgXF35cxFwUoZzShFeuNTaCrSmgAUx42Ng',
    "https://paper-api.alpaca.markets"
)

@conn.on(r'A$')
async def on_data(conn, channel, data):
    print(data)

conn.run(['A.SPY'])
```

Is there a way to get those updates (ideally in 1-minute or 5-minute intervals) using a paper trading account?

**Comment by ttt733** [comment]
Do you have a funded brokerage account with Alpaca? That (or a separate Polygon key) is needed to access the Polygon API.

**Comment by esoli2** [comment]
I see, thank you for the clarification. 

Following the documentation on Github, `For example, if you subscribe to account_updates, a WebSocket connects to Alpaca stream API, and if AM.* given to the subscribe() method, a WebSocket connection is established to Polygon's interface.`, I was hoping that the `A.*` would not be connecting to Polygon. 

Either way, all clear now. No live updates for me yet :(
