### ISSUE TITLE
api.polygon.earnings() does not return latest earnings

### ISSUE THREAD

**Issue by ShayanJa** [alpacahq/alpaca-trade-api-python#161]
I'm just curious if i'm doing something wrong here. I'm running the code like such 

```
api = tradeapi.REST(
    base_url=base_url,
    key_id=api_key_id,
    secret_key=api_secret
)
symbol = 'AAPL'
print(api.polygon.earnings(symbol))
print(api.polygon.financials(symbol))
```

When i look at both the earnings and the financials for apple i don't get back the most recent earning reports only up to 11/01/2018. Is anyone else experiencing this?

**Comment by ttt733** [comment]
It sounds like the last earnings date for Apple was pretty recent. Polygon might have missed it for some reason - you might want to check with them at support@polygon.io. The code looks fine, though.
