### ISSUE TITLE
Where can I find the Article related to this coding?

### ISSUE THREAD

**Issue by Chimera777** [alpacahq/alpaca-trade-api-python#167]
Before I clicked on this github link, I was reading the article about this AI. Can someone send me the article link please because I lost it?

Thanks in advance.

**Comment by shlomikushchi** [comment]
you could check this: https://alpaca.markets/docs/api-documentation/

**Comment by Chimera777** [comment]
Thanks sir :)

**Comment by umitanuki** [comment]
👍
