### ISSUE TITLE
Max retries exceeded with url: /v2/clock 

### ISSUE THREAD

**Issue by mrmushfiq** [alpacahq/alpaca-trade-api-python#169]
Connection was failing tonight every now and then. Market was closed though. Did not see this issue earlier

```
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paper-api.alpaca.markets', port=443): Max retries exceeded with url: /v2/clock (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f86c1357860>: Failed to establish a new connection: [Errno 111] Connection refused',))


```

**Comment by shlomikushchi** [comment]
is this something that still happens? was it a one time issue or is it reproducible?

**Comment by mrmushfiq** [comment]
It didn't happen anymore. Just one night. However there was one more issue I encountered before that. When the market was closed  the clock.is_open() returned True (in the middle of the night). I haven't seen anything like that recently. I will post if I see anything like that on my logs. I run the script 24 hours.

**Comment by shlomikushchi** [comment]
ok. let us know if you get something like this again.
