### ISSUE TITLE
Update Polygon last trade and last quote to use v2

### ISSUE THREAD

**Issue by nickjohnson22** [alpacahq/alpaca-trade-api-python#171]

**Comment by shlomikushchi** [comment]
Hi Nick
I checked it and it seems to work fine, but documentation (https://polygon.io/docs/#get_v1_last_quote_stocks__symbol__anchor) is still V1
where did you see the updated docs?

**Comment by nickjohnson22** [comment]
I withdrew the request because Polygon hasn't updated their docs yet. They have told me those docs will updated within a week or so.

**Comment by shlomikushchi** [comment]
closing this issue since api still works with v1:
![image](https://user-images.githubusercontent.com/7924802/103036893-6bf97c00-4573-11eb-86f9-2a6d09b6ef68.png)
