### ISSUE TITLE
key_id is not set correctly in StreamConn constructor for polygon.StreamConn

### ISSUE THREAD

**Issue by allenjsomb** [alpacahq/alpaca-trade-api-python#187]
https://github.com/alpacahq/alpaca-trade-api-python/blob/37cae354e908203e1a87e788f9a38f26e7be7761/alpaca_trade_api/stream2.py#L170-L171

Instead of passing the key_id to the constructor it is getting set to empty string if the base_url doesn't contain staging.  It should pass the key_id unmodified instead of empty string.

**Comment by umitanuki** [comment]
Good catch, seems like it got broken in #178

**Comment by shlomikushchi** [comment]
this was fixed on April, 28. closing.
