### ISSUE TITLE
list_assets() doesn't fetch all available tickers

### ISSUE THREAD

**Issue by datadaddy1** [alpacahq/alpaca-trade-api-python#193]
Can we add the following from Polygon to get all available tickers on Polygon?

https://polygon.io/docs/#get_v2_reference_tickers_anchor

10-15% of tickers under REST.list_assets are not found when using Polygon to pull data.

**Comment by umitanuki** [comment]
Polygon and Alpaca universes are not expected to match 100%, as Polygon service is data provider while Alpaca's service is trading. Alpaca universe scopes (past and) present tradeable assets.
