### ISSUE TITLE
Polygon Split endpoint seems to have changed.

### ISSUE THREAD

**Issue by mufniarz** [alpacahq/alpaca-trade-api-python#200]
Getting Errors when attempted to use the api.polygon.splits(symbol) method.

Currently getting:
HTTPError: 404 Client Error: Not Found for url: https://api.polygon.io/v1/meta/symbols/AAPL/splits?apiKey=<apikey>

Works when accessing the endpoint:
https://api.polygon.io/v2/reference/splits/AAPL?apiKey=<apikey>

Using alpaca-trade-api==0.46

**Comment by umitanuki** [comment]
That's good to know...
