### ISSUE TITLE
historic_agg_v2 TypeError: Parser must be a string or character stream, not Timestamp

### ISSUE THREAD

**Issue by Devination** [alpacahq/alpaca-trade-api-python#205]
You used to be able to pass datetime objects to the v1 version of this function. Now it fails with these error messages.
```
TypeError: Parser must be a string or character stream, not Timestamp
TypeError: Parser must be a string or character stream, not datetime
```

**Comment by shlomikushchi** [comment]
I added some comments on your PR (required fixes to make it a bit better)
but
I will copy the same note I wrote there too:
in my opinion - we should select one acceptable format for all users.
if we do accept this change - users could use 4 different formats.
there's no need for such flexability (it will cause confusion and contradicting examples/documentation in the long run)

if we do allow one argument type only, the users will do the conversions on their end (and it's a very simple conversion) and we will have consistancy.

**Comment by shlomikushchi** [comment]
merged in https://github.com/alpacahq/alpaca-trade-api-python/pull/210
