### ISSUE TITLE
Limit buy did not execute

### ISSUE THREAD

**Issue by rmsyed** [alpacahq/alpaca-trade-api-python#207]
I found a peculiar situation in my paper trading account today. I placed a limit buy order for PHM at $35.39 when the market opened (9:30am). I eventually cancelled the order 15 minutes later because it didn't get filled. However, looking at PHM's movements today, there were clearly at least several minutes in this time frame where the stock price was below this limit.

Why didn't alpaca fill this order? It seems strange because when I tried another limit buy later in the day and the market price was below the limit order it did successfully fill.

**Comment by t-shah** [comment]
Usually this happens with lower volume stocks where different exchanges and wide spreads could cause odd behavior especially with odd lot sizes. PHM on the other hand, trades with decent volume and like you said was under limit for several minutes.

If you entered the order correctly this behavior seems unusual. It's typically easier to get fills on paper accounts.

**Comment by rmsyed** [comment]
Thanks for the quick reply! I agree, this seems really weird, especially given that PHM is not low-volume. Its hard to tell what went wrong since there were no errors or warning messages either. Here is the printout of the Order object in Python, if it helps:

```
Order({'asset_class': 'us_equity',
    'asset_id': '96f6e02d-e110-40c7-bff6-ade1c0e451c4',
    'canceled_at': '2020-06-03T13:45:01.432029Z',
    'client_order_id': '<redacted>',
    'created_at': '2020-06-03T13:30:01.580264Z',
    'expired_at': None,
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'id': '<redacted>',
    'legs': None,
    'limit_price': '35.39',
    'order_class': '',
    'order_type': 'limit',
    'qty': '1412',
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': 'buy',
    'status': 'canceled',
    'stop_price': None,
    'submitted_at': '2020-06-03T13:30:01.56018Z',
    'symbol': 'PHM',
    'time_in_force': 'day',
    'type': 'limit',
    'updated_at': '2020-06-03T13:45:01.446069Z'})
```

**Comment by rmsyed** [comment]
Update: I contacted Alpaca directly about this situation and this appears to have been a problem with paper trading specific to yesterday. The problem appears to have been solved.

**Comment by umitanuki** [comment]
Thanks for the update. Closing now. Please email to Alpaca support for live order issues when it happens.
