### ISSUE TITLE
historic_agg_v2.df Does not return vw

### ISSUE THREAD

**Issue by MrMitch17** [alpacahq/alpaca-trade-api-python#212]
Hello:

I noticed that when returning api.polygon.historic_agg_v2 it returns the vwap  but when requesting the datafram the vwap is not there.  It looks like it might need to be added to the mappings.

**Comment by shlomikushchi** [comment]
Hi, I just executed this: 
![image](https://user-images.githubusercontent.com/7924802/84417875-ef2e3280-ac1e-11ea-8b48-4e1fdc49dedd.png)

what version are you using?

**Comment by shlomikushchi** [comment]
you could also use the code from this branch in the meantime: 
https://github.com/alpacahq/alpaca-trade-api-python/pull/215

**Comment by MrMitch17** [comment]
Great. Thanks!
