### ISSUE TITLE
Corrupt data with LIVE trading for the first few seconds from starting up

### ISSUE THREAD

**Issue by nelfata** [alpacahq/alpaca-trade-api-python#217]
I am experiencing some corrupt data upon starting up the script and printing data from ```next()```.
The data I have seen is the value in:
```self.datetime.date()```
```self.getposition(d).size```
```
DATE  TIME     SYMBOL       SIZE             time.time()
06-10 00:00:00 TVIX: CHECK  121.96 0.00 0.00 1591899222.070981
06-10 00:00:00 TVIX: CHECK  121.96 0.00 0.00 1591899222.0719814
06-11 00:00:00 TVIX: CHECK  171.85 0.00 0.00 1591899222.2689812
06-11 14:13:36 TVIX: CHECK  170.90 0.00 0.00 1591899222.5389812
06-11 14:13:37 TVIX: CHECK  170.90 0.00 0.00 1591899222.809981
06-11 14:13:38 TVIX: CHECK  171.12 0.00 0.00 1591899223.090981
```
For the live data feed, the first two rows have the DATA/TIME incorrect as well as the position size. The third row shows the time incorrect.
The data starts becoming valid on the 4th row.

**Comment by shlomikushchi** [comment]
(same note for this issue)
there's a repo specifically for the backtrader integration. so this issue belongs there.
https://github.com/alpacahq/alpaca-backtrader-api
let's move it there.
also, try installing the most updated code for both packages like so:
`pip install -U git+https://github.com/alpacahq/alpaca-trade-api-python`
`pip install -U git+https://github.com/alpacahq/alpaca-backtrader-api`
and let's see if this issue still occurs.

**Comment by shlomikushchi** [comment]
moved here: https://github.com/alpacahq/alpaca-backtrader-api/issues/70
