### ISSUE TITLE
Return the unix timestamp in Polygon DataFrame

### ISSUE THREAD

**Issue by MrMitch17** [alpacahq/alpaca-trade-api-python#220]
I'm working on getting a full days worth of trades from polygon.  I noticed that the SIP timestamp that you need to use as the next offset is converted to a DateTime type and then used as the index.  This makes it so you have to then re-convert the date back into Unix to then feed it into the offset to get the next batch of trades.  It might be useful to have the SIP timestamp as an available returned value.

**Comment by shlomikushchi** [comment]
you could access the `raw` response. e.g
```py 
api.polygon.historic_agg_v2('AAPL', 1, 'day', _from='2019-01-01', to='2019-1-3')[0]._raw['timestamp']```

it will give you the timestamp

if on the other hand you do this: 
```py 
api.polygon.historic_agg_v2('AAPL', 1, 'day', _from='2019-01-01', to='2019-1-3')[0].timestamp
```
you will get this:
```Timestamp('2019-01-02 00:00:00-0500', tz='America/New_York')```

**Comment by MrMitch17** [comment]
Ok cool. I was trying to stick with strictly data frames to keep everything in pandas.  But now that you brought that up.  If I return the object, then just don't use .df, then I should be able to get the timestamp that I'm looking for to feed it back into getting the next set of historic trades and use the .df to then do the actual recording of the data.  

I'm opening these issue so you guys know what I'm running into as a new user of the python package trying to get a dump of daily trades and Aggs.
