### ISSUE TITLE
long-short

### ISSUE THREAD

**Issue by evrenbingol** [alpacahq/alpaca-trade-api-python#221]
https://github.com/alpacahq/alpaca-trade-api-python/blob/master/examples/long-short.py

I see a line where it allocates amount for short and long

self.shortAmount = equity * 0.30
self.longAmount = equity + self.shortAmount

does not this suppose to be 
self.shortAmount = equity * 0.30
self.longAmount = equity - self.shortAmount (where you allocate the remaining 60%)

Thanks

**Comment by shlomikushchi** [comment]
Hi,
thanks for the heads up
I will make sure we didn't miss anything and add the change

**Comment by shlomikushchi** [comment]
this was added here: https://github.com/alpacahq/alpaca-trade-api-python/commit/c0b24de
closing.
