### ISSUE TITLE
RuntimeError (no event loop.)

### ISSUE THREAD

**Issue by dans-acc** [alpacahq/alpaca-trade-api-python#222]
When the StreamConn run method is invoked from a thread that is _not the main thread_ a RuntimeError is thrown; asyncio loop not present.

**The cause:**
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/dans-acc/miniconda3/envs/bot-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/dans-acc/Workbench/Bot/bot/stream.py", line 171, in run
    self._init_apca_conn()
  File "/Users/dans-acc/Workbench/Bot/bot/stream.py", line 61, in _init_apca_conn
    base_url=self.apca_url)
  File "/Users/dans-acc/miniconda3/envs/bot-env/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 27, in __init__
    self.loop = asyncio.get_event_loop()
  File "/Users/dans-acc/miniconda3/envs/bot-env/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.

**Thrown by:**
```python
if self._local._loop is None:
            raise RuntimeError('There is no current event loop in thread %r.'
                               % threading.current_thread().name)
```

**The fix needs to catch the RuntimeError analogous to the caught websockets.WebSocketException:**
```python
try:
            self.loop = asyncio.get_event_loop()
        except websockets.WebSocketException as wse:
            logging.warn(wse)
            self.loop = asyncio.new_event_loop()
            asyncio.set_event_loop(self.loop)
```

_I will shortly make a pull request that catches this issues._

Best,

Dans

**Comment by dans-acc** [comment]
**I've made a pull request, the fix:**
```python
        try:
            self.loop = asyncio.get_event_loop()
        except (websockets.WebSocketException, RuntimeError) as e:
            logging.warn(e)
            self.loop = asyncio.new_event_loop()
            asyncio.set_event_loop(self.loop)
```

**Comment by shlomikushchi** [comment]
Hi Dans, 
first of all thank a lot for the contribution and the issue alert.
the thing is, the calling code could be called from the main thread, or as you saw from a thread. 
who decides that? the developer writing the code.
that is why we let the developer take care of the event loop
as you can see in other issues and PRs regarding this:
https://github.com/alpacahq/alpaca-trade-api-python/pull/194
https://github.com/alpacahq/alpaca-trade-api-python/pull/179
https://github.com/alpacahq/alpaca-trade-api-python/pull/177

**Comment by dans-acc** [comment]
Thank you for the clarification! 

Best,

Dans.
