### ISSUE TITLE
Data streaming broken on version 0.48 but not on v0.46 ('AM.*')

### ISSUE THREAD

**Issue by duhfrazee** [alpacahq/alpaca-trade-api-python#226]
Just spent way too many hours of my life to figure out what was causing the problem :/

I have a project streaming ['AM.*', 'trade_updates'] on alpaca-trade-api v0.46. Everything works as expected.

On another project, I had the exact same code but only 'trade_updates' were working. The difference was alpaca-trade-api v0.48. Not sure if this is related to Alpaca's new data streaming but something broke between these two versions. Just wanted to make you and others aware.

Note: I was streaming using paper credentials, not sure about live.

My code:
```python
self._on_minute_bars = self.paper_conn.on(r'^AM$')(self._on_minute_bars)
self._on_trade_updates = self.paper_conn.on(r'trade_updates$')(self._on_trade_updates)
```

**Comment by shlomikushchi** [comment]
Hi
in v0.48 we added the alpaca data api.
so now you have 2 data apis (alpaca and polygon)
the way to register to alpaca data is by adding the `alpacadatav1` prefix
you could see it in the readme:
![image](https://user-images.githubusercontent.com/7924802/85229896-340f5180-b3f5-11ea-939e-2ced2395d5f1.png)

I think this will make the difference for your code

**Comment by duhfrazee** [comment]
Sorry for the delay. I was under the impression that polygon was sticking around and would be unimpacted. Is that incorrect in v0.48? I am using the polygon streaming still at AM.* That is what I noticed as being broken

**Comment by shlomikushchi** [comment]
there's no change in the data streams.
just note that the polygon api can only be used in funded accounts
if that is the case, I will test it today. let me know

**Comment by duhfrazee** [comment]
Yes I have a funded account. I am using the exact same code in v0.46 which has the same requirement and everything is working fine. Here is more of my code:

```python
channels = ['AM.*', 'trade_updates']
paper_conn = tradeapi.StreamConn(
        PAPER_APCA_API_KEY_ID,
        PAPER_APCA_API_SECRET_KEY,
        PAPER_APCA_API_BASE_URL
    )

tPWS = threading.Thread(
      target=paper_conn.run, args=[channels])
tPWS.start()

self._on_minute_bars =\
      self.paper_conn.on(r'^AM$')(self._on_minute_bars)
self._on_trade_updates =\
      self.paper_conn.on(r'trade_updates$')(self._on_trade_updates)

async def _on_minute_bars(self, conn, channel, bar):
# code here to catch bars

async def _on_trade_updates(self, conn, channel, account):
# code here to catch trade_updates
```

I believe that's all the related code I am using to run it.

To clarify, here's what I am experiencing:
v0.46: trade_updates and polygon data streaming are working as expected
v0.48: only trade_updates are coming through. No polygon data streaming.

Hope this helps

**Comment by shlomikushchi** [comment]
Hi
sorry for the delay
in version 0.48 we added another data stream defaulting to alpaca data stream
to use the polygon data stream one must specify it explicitly

![image](https://user-images.githubusercontent.com/7924802/86631519-e5f27480-bfd6-11ea-8e3c-2518f7c86e69.png)

so your StreamConn should look like this:

```py
paper_conn = tradeapi.StreamConn(
        PAPER_APCA_API_KEY_ID,
        PAPER_APCA_API_SECRET_KEY,
        PAPER_APCA_API_BASE_URL
        data_stream='polygon'
    )
```

**Comment by duhfrazee** [comment]
No worries. Okay great. Didn’t realize there was a breaking change. Thanks for the clarification.
