### ISSUE TITLE
Polygon Historic Trades Not Working

### ISSUE THREAD

**Issue by avlewis** [alpacahq/alpaca-trade-api-python#227]
Im trying to get historic trades but am getting a error

My Code:
`aapl_o = api.polygon.historic_trades_v2('AAPL', date='2019-02-02')
`
Error:
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.polygon.io/v2/ticks/stocks/trades/AAPL/2019-02-02?timestamp=1&apiKey=AK*******`

This also occurs with historic quotes, as far as I can tell everything else works as expected

**Comment by shlomikushchi** [comment]
Hi
I think this is a polygon issue. doing the same request for the next days, work
![image](https://user-images.githubusercontent.com/7924802/85145517-55393c00-b255-11ea-8e18-d89b9c24f3c2.png)

and quotes:

![image](https://user-images.githubusercontent.com/7924802/85145553-671adf00-b255-11ea-828f-8b5172b828f2.png)

I see the same thing you do for that date

**Comment by avlewis** [comment]
Just a weird coincidence but arbitrary date I must have chosen was apparently a day the market was closed. Thank you for the quick response though, it was definitely a user error!
