### ISSUE TITLE
Installation error on windows 10

### ISSUE THREAD

**Issue by riodda** [alpacahq/alpaca-trade-api-python#230]
Hi, i've tryed to install alpaca trading api trough conda without success. Using pip on windows i have error about 2 incompatible requirements:

ERROR: worldtradingdata 0.1.5 has requirement pytest==5.0.1, but you'll have pytest 5.4.3 which is incompatible.
ERROR: worldtradingdata 0.1.5 has requirement urllib3==1.25.3, but you'll have urllib3 1.24.3 which is incompatible.

**Comment by shlomikushchi** [comment]
Hi
this seems like an issue with another package (worldtradingdata)
if you don't need both packages in the same project, just use virtualenv to install the packages in an isolated environment.

if you need both, installing one over the other does give that error you mentioned, but it still installs everything correctly
![image](https://user-images.githubusercontent.com/7924802/85229689-070e6f00-b3f4-11ea-8620-3f124db32755.png)

as can be seen here:
![image](https://user-images.githubusercontent.com/7924802/85229704-1b526c00-b3f4-11ea-9a95-246ec0f89923.png)
