### ISSUE TITLE
polygon/REST.historic_agg_v2

### ISSUE THREAD

**Issue by Millerlm012** [alpacahq/alpaca-trade-api-python#247]
Hi!

I'm trying to pull historical data for a certain date and I only want the market hours (9:30 to 16:00). I can pull the data for a specified date fine using...
![alpaca_working](https://user-images.githubusercontent.com/44953936/86022507-17c07580-b9f0-11ea-8cde-9de40f422b03.png)
But as mentioned in the documentation at [Alpaca Documentation](https://github.com/alpacahq/alpaca-trade-api-python#polygonresthistoric_agg_v2self-symbol-multiplier-timespan-_from-to-unadjustedfalse-limitnone) underneath polygon/REST.historical_agg_v2(), it says I should be able to use datetime.datetime as an acceptable format, but whenever I use any form of datetime.datetime I get an error looking like...
![alpaca_bug_datetime_error](https://user-images.githubusercontent.com/44953936/86022877-8f8ea000-b9f0-11ea-817f-b93762f0848b.png)
and going to the internal server error URL given I get... 
![alpaca_bug_polygons_error](https://user-images.githubusercontent.com/44953936/86023033-c1076b80-b9f0-11ea-8a1b-4bbd1e913d73.png)
Does polygon not support that and alpaca needs to update their documentation? Is there a way to get the historical data using polygon/REST.historical_agg_v2() for a particular date? Or is there something else that I could try? Thanks in advance!

**Comment by duhfrazee** [comment]
Polygon API likes time to be in microseconds for some reason
This may help:
```python
_from = int(EASTERN.localize(
            datetime.datetime.combine(date, market_open_time)).timestamp()*1000)
to = int(EASTERN.localize(
            datetime.datetime.combine(date, market_close_time)).timestamp()*1000)
```

**Comment by Millerlm012** [comment]
Yes I was able to make this work and I'll keep that in mind for the future. Thank you!

**Comment by shlomikushchi** [comment]
here's a full example code that give the desired result:
```py
import pytz
NY = 'America/New_York'

start=pytz.timezone(NY).localize(datetime(2020,1,2,9,30)).timestamp()*1000  # timestamp in micro seconds
end=pytz.timezone(NY).localize(datetime(2020,1,2,16,0)).timestamp()*1000
df=api.polygon.historic_agg_v2('AAPL', 1, 'minute', _from=start, to=end).df
```
