### ISSUE TITLE
historic_trades_v2 parameters/Doc miss match

### ISSUE THREAD

**Issue by evrenbingol** [alpacahq/alpaca-trade-api-python#248]
When you only have limit I get this error. 
TypeError: historic_agg_v2() missing 2 required positional arguments: '_from' and 'to'

Doc reads :
Specify the _from parameter if you specify the to parameter since when to is specified _from is assumed to be the beginning of history. Otherwise, when you use only the limit or no parameters, the result is returned from the latest point.

api.polygon.historic_agg_v2(symbol,1,"minute", limit=1000) -> this should be valid.

**Comment by shlomikushchi** [comment]
Hi thanks for your input. check the PR I added.
