### ISSUE TITLE
Loosen up the requirements

### ISSUE THREAD

**Issue by mLewisLogic** [alpacahq/alpaca-trade-api-python#252]
Related to: https://github.com/alpacahq/alpaca-trade-api-python/issues/230

Specifying exact versions for a 3rd party package is not a very friendly practice.
Locking to exact versions is critical for a production application, but for libraries that will be consumed by others, you generally want version specifications as wide as possible (without breakage).

Python has its warts with dependency management, but locking to specific versions is going to magnify those by an order of magnitude and virtually guarantee version incompatibilities as an app grows (along with its dependencies).

**Comment by mLewisLogic** [comment]
For color, this doubly goes for "basic" libs (like requests, urllib, ws, etc) that basically every sizeable networking app is bound to inherit as a dep sooner or later.

I'm looking specifically at these:

# pandas<0.23
What breaks if `alpaca-trade-api-python` is run with Pandas `0.23`? This holds a Pandas-dependent app back from upgrading. I'm sure you can imagine that your users would like to do data analysis as part of their trading operations.


# requests==2.24.0
Way too specific here.

# urllib3==1.24.3
Way too specific as well

# websocket-client==0.57.0
Same.

# alpha_vantage==2.2.0
This one is probably fine given that it's an esoteric lib that is less likely of hitting conflict. Again though, why the exact specification here? Maybe it needs [asyncio support](https://github.com/RomelTorres/alpha_vantage#news)? Probably makes sense to switch it to a `>=2.2.0` in that case to unlock minor version upgrades.

**Comment by mLewisLogic** [comment]
Actually, was thinking about the Pandas issue a little more. That really should be left open-ended in this lib.
If `pylivetrader` wants to specify a specific Pandas requirement (due to `zipline`), that can be done there. There's no reason to push that requirement down into this repo.

**Comment by mLewisLogic** [comment]
Related to: https://github.com/alpacahq/alpaca-trade-api-python/issues/242

**Comment by shlomikushchi** [comment]
Hi
thanks for the comments
about pandas, basically we wanted the behavior to be the same all across our packages.
but when using pylivetrader, the user doesn't have direct access to the alpaca-trade-api, so I'm thinking it's ok to have different restrictions (I am a bit concerned about different behavior underneath the interface, but it should probably be ok)

about the other packages, we use pyup, which requires explicit package versioning. the logic is that we always upgrade to the latest version and that this should not be an issue. we just started the integration so it will take some time to really work smoothly.

**Comment by mLewisLogic** [comment]
I get wanting explicit package versioning for an application, but for a 3rd party library consumed by others, it is going to cause a lot of problems and is very unpythonic.
For example, look at the requirements for `pyup` itself:
https://github.com/pyupio/pyup/blob/master/setup.py#L17-L28

It marks version dependencies that it strictly needs. It doesn't try to lock explicit versions into the library itself. That will virtually guarantee version incompatibilities in apps of any reasonable complexity.

**Comment by shlomikushchi** [comment]
python versioning is an issue.
doing something like "package >= X" is more comfortable but when then version of the other package changes you may get unexpected behavior or even worse, functions change and now your code doesn't work anymore even though you(the user) haven't changed nothing.
when specifying a specific version and another package specifies a different version (to my best recollection) it gives the user a warning but it still installs both packages.
I get what you're saying, don't get me wrong. 
maybe we could go for something like: "package>=1.x,<2" that way all minor/non breaking versions are still ok, but breaking versions are not automatically accepted

**Comment by mLewisLogic** [comment]
I'd be fine with locking to major versions.
In an ideal world, the requirements specify what strictly works, which can be something that CI helps establish. Obviously though that takes a lot of investment in testing to get set up thoroughly.

For many of the requirements, the "compatible release" version specifier could be useful: https://www.python.org/dev/peps/pep-0440/#compatible-release

For others, it might make sense to hand-curate a wider range. For instance, Pandas has significant use in the wild across both `0.2x` and `1.x`. I'd imagine that both would work fine for this library, since you're barely using any meaningful functionality. If `pylivetrader` wants a narrower requirement, it can do that fine without needing to impose into this lib.

```
when specifying a specific version and another package specifies a different version (to my best recollection) it gives the user a warning but it still installs both packages.
```
You're probably referencing pip here, which will complain, but in many cases will ignore. I'd nudge you to also think about more modern systems like `poetry` which will disallow this due to ambiguity and non-reproducibility. The goal for a production system handling large amounts of money should be reproducibility and consistency. That is best achieved by user app-level version locking (something that the user's `requirements.txt` or `pyproject.toml` file will specify).

**Comment by yousefa00** [comment]
Have there been any updates about this? I get an error when installing `pandas 0.22.0` and I'm not sure why. Anyone have any ideas?

**Comment by shlomikushchi** [comment]
I've created a PR for this issue, but we'll wait a bit before merging it I think.
1. we want to test it with our existing packages (pylivetrader, alpaca-backtrader-api) and also get community feedback so you are encouraged to install this branch and tell us if there are issues.
2. pandas is still an issue.
to work well with zipline we need to have this range of pandas: `pandas>=0.18.1` (zipline 1.3.0 specifies this version explicitly) 
that means we allow people to use pandas versions ranging back 4 years.
that is an issue
3. we need to think about another thing. many of the users of this package, or not python experts. they install this package, they write some algo logic, and they run it against the broker API. to many, this is their application and not a third party package. for those users, this is actually not a good thing to do

please, give us your opinions. 
they are welcome.

**Comment by mLewisLogic** [comment]
In terms of the relationship between this lib and `zipline/pylivetrader`, think of them as totally disjoint. Pip or poetry will handle the version compatibility intersection for you.
Specifying broad versions for this library is fine. Specify them as broad as will technically work. There is very little Pandas usage in here, so TBH, you'd probably be fine with a wide open `pandas` spec without version.
If `pylivetrader` depends upon this library _and_ has a tight `pandas` version dependency, let it specify it there. If a user app needs `pylivetrader` then it will use the tighter requirements from that to specify its final dependencies.
This library has _no_ dependency upon `pylivetrader`, so don't try to enforce one. `pylivetrader` has a dependency upon this lib, so that's where the dependency specification should go.

In a similar vein, if a user wants to prototype something and just run `pip install alpaca-trade-api`, it is actually best practice to keep the requirements as loose as will technically work. CI should protect you from errors that crop up from new dependency versions. Hard capping the dependency versions that you will allow your end users to use is user-hostile, and is a wasteful cat-and-mouse game for you.

I'd suggest inverting the perspective on this. The version dependencies should be loose by default, and should disallow version ranges that have problems (ie, before needed functionality was introduced in a library).
There is a little bit of a per-lib nuance to this as well. For instance, `requests` is very stable. Limiting the version on that is just counterproductive. Same with `urllib3`. These are libraries that are just in massively widespread use and their APIs are very stable.
Pandas had _some_ API changes when it hit 1.0, but it was a negligible amount. Almost certainly not anything that would affect this lib. Again, CI is what should be telling you if 1.0 broke something. Preventing people from running modern versions of a library because it _might_ break is a fear that will always hold back the adoption of this lib. Again, CI, or even manual checking is the right approach.

To get familiar with Python packaging best practices (esp around version specification) check out some prominent libraries (not apps). Those would have had lots of eyeballs/opinions/PRs on them and would be closer to best practice:
* [pyup](https://github.com/pyupio/pyup/blob/master/setup.py#L17-L28)
  - You'll notice here specific `>=` deps, likely related to specific needed functionality that was added then
  - Also, clear CI support to test (in an isolated tox environment) that would catch errors due to external version bumps
* [tensorflow](https://git.corp.stripe.com/stripe-sandbox/mfm-notebooks/tree/master/merchant_forecasting/monitoring_reserves/v4/models/hppm_opt)
  - Some specifics, but others are looser.
* [pandas](https://github.com/pandas-dev/pandas/blob/master/setup.py#L746-L749)
* [arrow](https://github.com/crsmithdev/arrow/blob/master/setup.py#L26-L29)
* [dateutil](https://github.com/dateutil/dateutil/blob/master/setup.cfg#L35)

**Comment by umitanuki** [comment]
Just wanted to give some color on this. I generally agree libraries should be more loose on the dependency pinning. That said, Alpaca SDK is a bit unique situation in that it's used as both a library and an application. For many newbie algo traders especially who come from trading space, just writing a shrot script to get started as an application, and this SDK library is already part of it. For those who are not expert in python area, some dependency umbiguity could be a headache.

All that said, I am good to try the suggestion above. Hope python ecosystem is a lot better than a few years ago that don't break things unexpectedly.

**Comment by shlomikushchi** [comment]
This was resolved as recommended. closing.
