### ISSUE TITLE
Streaming data prefix 'A.' is not supported when `data_stream != 'polygon'`

### ISSUE THREAD

**Issue by mLewisLogic** [alpacahq/alpaca-trade-api-python#253]
'A.*' is supported when `data_stream` is set to `'polygon'`, but not when left as `None` or set to `'alpacadatav1'`.

https://github.com/alpacahq/alpaca-trade-api-python/blob/0330f089accde6520c9d6d997909086ac8f1b9bc/alpaca_trade_api/stream2.py#L202-L212

**Comment by umitanuki** [comment]
Correct, since Alpaca data stream does not support `A.` at this point.

**Comment by mLewisLogic** [comment]
👍 
Thanks for the update. Will just use the Polygon API. (wasn't sure if it was an internal proxy or uniquely implemented functionality)
