### ISSUE TITLE
os environment variables ignored on windows (Jupiter)

### ISSUE THREAD

**Issue by riodda** [alpacahq/alpaca-trade-api-python#260]
Hi, i've tryed both to set the environment variable in windows and trough the os library 

os.environ["APCA_API_BASE_URL"] = "https://paper-api.alpaca.markets"

But whatever I do i have account error in return, is possible to explicit the base url in the api = tradeapi.REST constructor ?

`HTTPError: 404 Client Error: Not Found for url: https://api.alpaca.markets/v2/account

During handling of the above exception, another exception occurred:`

**Comment by shlomikushchi** [comment]
hi, 
you could just do this:
```py
tradeapi.REST(key_id=ALPACA_API_KEY,
              secret_key=ALPACA_SECRET_KEY,
              base_url="https://paper-api.alpaca.markets")
```

**Comment by riodda** [comment]
Quite simple actually ! I think is worth to be added in the docs !

**Comment by shlomikushchi** [comment]
it's there:
![image](https://user-images.githubusercontent.com/7924802/86785096-edfbf400-c06a-11ea-8f38-33daedb6fb99.png)

**Comment by riodda** [comment]
> it's there:
> ![image](https://user-images.githubusercontent.com/7924802/86785096-edfbf400-c06a-11ea-8f38-33daedb6fb99.png)

Yup, and base_url="https://paper-api.alpaca.markets" is missing and in the docs is specifyed to use env variables to switch between the live url and the paper url.
The fact that is a parameter of REST constructor is not specifyed in the docs.

**Comment by shlomikushchi** [comment]
you're talking about the base_url. sure I'll add it. was talking about the credentials

**Comment by riodda** [comment]
> you're talking about the base_url. sure I'll add it. was talking about the credentials

Yes, all the rest of the docs it's very clear !
