### ISSUE TITLE
Cancel orders by symbol?

### ISSUE THREAD

**Issue by leopoldsw** [alpacahq/alpaca-trade-api-python#264]
Is it possible to cancel orders by symbol, like `REST.cancel_order(symbol)`?

This is a really useful feature for some strategies.

**Comment by shlomikushchi** [comment]
Hi.
that is not possible
you can cancel orders by id
but you have 2 options to get the same functionality 
1. list orders and get the order for the symbol. e.g you can do this:
```py
[o for o in api.list_orders() if o.symbol == "AAPL"]
```
2. use `get_order_by_client_order_id()` give every order a unique id, get the order by that id, cancel the order

**Comment by leopoldsw** [comment]
Thanks for the answer.

Any particular reason why this feature is not available? If not, I would like to add a feature request.  As I mentioned in the original post, this is a really useful feature for some strategies.

**Comment by shlomikushchi** [comment]
so (my opinion) if we do something like that we could get ambiguous results. e.g: submitting a bracket order (3 orders for the same symbol). which one should we cancel?

**Comment by leopoldsw** [comment]
There can be two different functions. 

The case you mentioned is when cancel using order ID is helpful. But another case is that multiple orders are placed for one symbol, and if I just want to get out of the position for that symbol and cancel all orders associated with this symbol. 

Getting all orders, then filter by symbol is one way to accomplish this. But maybe a native function can be a little faster. 

😀
