### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by ksan01** [alpacahq/alpaca-trade-api-python#268]
Hi,
I am getting the http.client.RemoteDisconnected: Remote end closed connection without response error although I have a fast and stable internet connection.
I am using the Paper Trading version, I am guessing something is wrong with the server?

**Comment by shlomikushchi** [comment]
Hi, I am not aware of any server issues. working with the server as I'm writing this.
do you encounter this issue constantly? could you provide a sample algorithm to reproduce this issue?

**Comment by shlomikushchi** [comment]
closing due to lack of response
