### ISSUE TITLE
Create a StreamConn instance for polygon and paper trading alpaca

### ISSUE THREAD

**Issue by connor-roche** [alpacahq/alpaca-trade-api-python#277]
Is it possible to create a single StreamConn class that reaches out to grab stock data from Polygon, but gets trade updates from a paper trading account on Alpaca?

I think I need to use my live trading account key to access Polygon data, but that key is different than the key I want to use for trading updates.

The reason I ask is that it seems Alpaca market data streaming doesn't reliably send pre-market data. I tried it this morning with 1-minute aggregates and I only got responses from the stream every 10 mins or so for SPY and not at all for the other symbols.

Perhaps Polygon has a more reliable stream for pre-market data?

**Comment by shlomikushchi** [comment]
Hi, 
you can specify the credentials when you create the StreamConn
![image](https://user-images.githubusercontent.com/7924802/88369021-d1182e00-cd97-11ea-9296-6f91b863588b.png)

you can pass different credentials to different instances

**Comment by connor-roche** [comment]
Thanks, can I have more than one StreamConn instance open at a time? As long as one goes to Alpaca and the other to Polygon?

Also, does the Polygon StreamConn instance open in another thread or stay in the current thread? I only ask because Polygon's python client opens it's socket in a separate thread:
https://github.com/polygon-io/client-python/blob/7ec3bbaaa901997e26d6831313785b17a88beb69/polygon/websocket/websocket_client.py#L49

**Comment by shlomikushchi** [comment]
1. you can (hold both)
2. depends on you. the objects are using asyncio. so you can run the consume methods using asyncio.gather using the same event loop.
