### ISSUE TITLE
Allow omission of order type in submit_order()

### ISSUE THREAD

**Issue by umitanuki** [alpacahq/alpaca-trade-api-python#28]
Since supported order types are only the basic four ones, it is possible to determine the type from parameter set.

- if both limit_price and stop_price are specified, then limit stop
- if stop_price is specified but limit_price is not, then stop
- if limit_price is specified but stop_price is not, then limit
- otherwise, market

**Comment by bdowling** [comment]
I would think it would be preferable to be more explicit than implied in a financial API.  The caller should be required to include the order_type.  e.g. if somehow client coding error caused the inputs to be None, a market order could be accidentally placed.

**Comment by umitanuki** [comment]
Good feedback. Yes agree, that's a valid point.
