### ISSUE TITLE
asyncio error

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [alpacahq/alpaca-trade-api-python#288]
File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/stream2.py", line 287, in run
    loop.run_until_complete(self.consume())
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError

**Comment by shlomikushchi** [comment]
Hi, 
in the version you have installed there's a reconnection mechanism. so it should reconnect after this exception.
could you:
1. make sure you have the python logger configured
    in your main.py (or any other name you gave it) add these:
```py
      import logging
      logging.basicConfig(format='%(asctime)s %(message)s', level=logging.INFO)
```
2. make sure your `@conn.on()` methods wrap the code with `try except` blocks.
   if you have an exception in those blocks, it may throw an exception

some more questions:
1. did your execution stopped after that exception?
2. was it inside market hours, or outside of market hours?
