### ISSUE TITLE
[Feature]: Add option that would allow return raw response from API

### ISSUE THREAD

**Issue by MaximZemskov** [alpacahq/alpaca-trade-api-python#305]
Hey.

Is it possible to add option to `REST` object that would allow to return raw response instead of `Entity`?

Something like that:

```python
client = tradeapi.REST(raw_response=True)

resp = client.get_account()
print(resp)
{
  "account_blocked": False,
  "account_number": "010203ABCD",
  "buying_power": "262113.632",
  "cash": "-23140.2",
  "created_at": "2019-06-12T22:47:07.99658Z",
  "currency": "USD",
  "daytrade_count": 0,
  "daytrading_buying_power": "262113.632",
  "equity": "103820.56",
  "id": "e6fe16f3-64a4-4921-8928-cadf02f92f98",
  "initial_margin": "63480.38",
  "last_equity": "103529.24",
  "last_maintenance_margin": "38000.832",
  "long_market_value": "126960.76",
  "maintenance_margin": "38088.228",
  "multiplier": "4",
  "pattern_day_trader": False,
  "portfolio_value": "103820.56",
  "regt_buying_power": "80680.36",
  "short_market_value": "0",
  "shorting_enabled": True,
  "sma": "0",
  "status": "ACTIVE",
  "trade_suspended_by_user": False,
  "trading_blocked": False,
  "transfers_blocked": False
}
```

It will help to build API's that uses Alpaca API responses.
I understand that it could easily be solved on user side, but it will be not clean.

It looks like this problem is very easy to solve:

```python
def get_account(self) -> Account:
    """Get the account"""
    resp = self.get('/account')
    if self._raw_response:
        return resp
    return Account(resp)
```

**Comment by shlomikushchi** [comment]
Hi,
for each api response object there's a property called `_raw` with a dictionary object with the data.
something like this:
```py
account = api.get_account()
print(account._raw)

--- results in:
```
![image](https://user-images.githubusercontent.com/7924802/91976655-f6e70a00-ed29-11ea-87c3-a2a44dcdd316.png)

does this helps?

**Comment by shlomikushchi** [comment]
Hi,
for each api response object there's a property called `_raw` with a dictionary object with the data.
something like this:
```py
account = api.get_account()
print(account._raw)

--- results in:
```
![image](https://user-images.githubusercontent.com/7924802/91976717-13834200-ed2a-11ea-8a17-55b17d5745e7.png)


does this helps?

**Comment by MaximZemskov** [comment]
Yeah, I saw this property. But it looks like the property is protected and it's not good to rely on it. Is it protected/private? If it's not, the issue will be solved

**Comment by shlomikushchi** [comment]
so, there's no real protected properties in python it's just semantic. you could rely on that to be accessible and true
