### ISSUE TITLE
Polygon all_tickers returns empty list on Weekends

### ISSUE THREAD

**Issue by miketoastmacneil** [alpacahq/alpaca-trade-api-python#310]
Running the following gives an empty list of `Symbol` objects when run on weekends.

```
import alpaca_trade_api as tradeapi

api = tradeapi.REST()
tickers = api.polygon.all_tickers()
tickers
[]
```

Checked the implementation and looks like it grabs the most recent day snapshot which may not work on a Saturday (which is when us retail guys are doing some research). Took a look and a kind of invasive approach could be to swap this out for a call to grouped daily, but not sure.

**Comment by tjquinn1** [comment]
@miketoastmacneil did you figure anything out with this? I am facing the same problem. It also happens with gainers_losers()

**Comment by shlomikushchi** [comment]
Hi
`all_tickers()` and `gainers_losers()`  are snapshots that according to the polygon docs: 
```yaml
Snapshot data is cleared at 12am EST and gets populated as data is received from the exchanges.
```
it is rebuilt every trading day (so it's not available during the weekend)

The other option is to use a different api `/v2/reference/tickers` but that api returns a maximum of 50 tickers per trade, so getting all will take a very long time (could easily result in 200 api calls) which is not what a user wants when a ticker list is needed.

The right approach is to get the ticker list from Alpaca and then get the data either from alpaca or polygon.
In any case, if you want to trade with Alpaca - you could only trade tickers that are supported by Alpaca, so no point on getting the ticker list from polygon (get the data from polygon if you want though)

**Comment by tjquinn1** [comment]
@shlomikushchi  Thanks for the answer.

**Comment by miketoastmacneil** [comment]
Sorry about the late response here but thank you @shlomikushchi. @tjquinn1 This is what I ended up doing.

`
import alpaca_trade_api as tradeapi
from tqdm import tqdm

"""
Pulls polygon company descriptions for each asset listing
offered by alpaca.
"""

api = tradeapi.REST()
alpaca_assets = api.list_assets()

companies = []
for asset in tqdm(alpaca_assets):
    description = api.polygon.company(asset.symbol)
    if description is not None:
        companies.append(description.__dict__)
`
