### ISSUE TITLE
recent earnings and dividends data omitted for the alpaca API wrapper to polygon

### ISSUE THREAD

**Issue by kartiksubbarao** [alpacahq/alpaca-trade-api-python#313]
I'm seeing recent data omitted for earnings and dividends returned by the alpaca wrapper to the polygon API. For example, calling the polygon API directly for Apple's dividends yields 2020-05-08 as the most recent dividend:

```
curl -s "https://api.polygon.io/v2/reference/dividends/AAPL?apiKey=ALPACA_KEY_ID" | jq '.results[0]'  
{
  "ticker": "AAPL",
  "exDate": "2020-05-08",
  "paymentDate": "2020-05-14",
  "recordDate": "2020-05-11",
  "amount": 0.82
}
```

However, the same call with the alpaca wrapper returns 2018-11-08 as the most recent dividend:

```
In [45]: api.polygon.dividends('AAPL')[0]
Out[45]: 
Dividend({   'amount': 0.73,
    'declaredDate': '11/01/2018',
    'exDate': '11/08/2018',
    'indicated': 0.73,
    'paymentDate': '11/15/2018',
    'qualified': 'Q',
    'recordDate': '11/12/2018',
    'symbol': 'AAPL',
    'type': 'D'})
```
Also, the polygon data seems to be missing an even more recent dividend on 2020-08-07.

**Comment by WillieMaddox** [comment]
Same here.  dividends 2 year old and older are the most recent results the alpaca wrapper returns.

**Comment by kartiksubbarao** [comment]
@WillieMaddox Alpaca just recently announced that the wrapper is being discontinued, so it looks like the alpaca part of this issue is moot now.

**Comment by drew887** [comment]
Hey closing this one out due to inactivity and that polygon is now removed.
