### ISSUE TITLE
WARNING:root:code = 1009 (message too big), no reason

### ISSUE THREAD

**Issue by dinnu93** [alpacahq/alpaca-trade-api-python#319]
I'm simply trying to stream the data of all NASDAQ aggregate minute bar data. and I'm getting the above error.
@shlomikushchi would be very thankful if you can help me with this issue :)

## ERROR

```
3610
authorized
Entity({'action': 'authenticate', 'status': 'authorized'})
listening
Entity({'streams': ['trade_updates']})
authorized
Entity({'action': 'authenticate', 'status': 'authorized'})
WARNING:root:code = 1009 (message too big), no reason
Traceback (most recent call last):
  File "paper.py", line 34, in <module>
    conn.run(['trade_updates']+symbol_list[:700])
  File "/Users/dinesh/Desktop/muon-capital/lib/python3.8/site-packages/alpaca_trade_api/stream2.py", line 298, in run
    loop.run_until_complete(self.consume())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError

```

## CODE
```
conn = StreamConn(key_id=KEY_ID, secret_key=SECRET_KEY, base_url=BASE_URL, data_url=DATA_URL, data_stream='alpacadatav1')
api = tradeapi.REST(key_id=KEY_ID, secret_key=SECRET_KEY, base_url=BASE_URL)
account = api.get_account()
assets = api.list_assets(status="active", asset_class="us_equity")
assets = filter(lambda a: a.exchange == "NASDAQ", assets)

def get_alpaca_symbol(asset):
	symbol = asset.symbol
	return 'alpacadatav1/AM.'+symbol

symbol_list = list(map(get_alpaca_symbol, assets))

print(len(symbol_list))


@conn.on(r'.*')
async def on_data(conn, channel, data):
    print(channel)
    pprint(data)

# A.SPY will work, because it only goes to Polygon
# conn.run(['A.SPY'])

# account_updates fail, being sent to websocket stream
conn.run(['trade_updates']+symbol_list)

```

**Comment by shlomikushchi** [comment]
Hi @dinnu93 
nice code snippet, uncommon style

about your issue:
1. you can only get data stream during market hours
2. you can't subscribe to 3000+ stocks. there are limits: https://alpaca.markets/docs/api-documentation/api-v2/market-data/streaming/

**Comment by dinnu93** [comment]
* There is no limit for the number of channels with minute bars (AM.). @shlomikushchi 

Is written on the link you've mentioned above.
That's why I'm trying only AM

**Comment by shlomikushchi** [comment]
the messages come in one by one, so I don't believe this is a python package issue. might be an api limit.
maybe in the registration part.. maybe that's a too long message
because when subscribed, you pass a list, maybe a list over 650 elements in your case causes an issue (trying to think)

**Comment by dinnu93** [comment]
https://github.com/gorilla/websocket/issues/283 This looks very related to my above issue.

**Comment by shlomikushchi** [comment]
what is the added information? you're thinking it's a server side limit?

**Comment by dinnu93** [comment]
I think it's a limit set by the alpaca-api or my browser or python websocket api itself, something is setting a limit of how many bytes a websocket message should be and I'm unable to figure out at what point down the stack is the limit being set.

**Comment by shlomikushchi** [comment]
we are using the websockets package. maybe this will help: https://websockets.readthedocs.io/en/stable/design.html?highlight=read_limit#buffers

**Comment by dinnu93** [comment]
Thanks @shlomikushchi this is one step closer to what I'm looking for. I guess I'll fork the library and change the read_limit to suit my needs 👍
