### ISSUE TITLE
get_barset() does not support 'limit' and 'start' args together

### ISSUE THREAD

**Issue by cechmanek** [alpacahq/alpaca-trade-api-python#324]
The `start` argument is ignored if a value for the `limit` arg is passed.

steps to reproduce:
```
import alpaca_trade_api
import pandas as pd

alpaca_api = alpaca_trade_api.REST(key_id=key_id, secret_key=secret_key, base_url=endpoint, api_version=None, oauth=None)
start =  pd.Timestamp(year=2016, month=1, day=1).isoformat()
start =  pd.Timestamp(year=2016, month=1, day=1, tz='US/Central').isoformat() # wrong result with or without timezone

print('getting barset starting from', start)

wrong_bars = alpaca_api.get_barset('AAPL', '5Min', limit=100, start=start)
correct_bars = alpaca_api.get_barset('AAPL', '5Min', start=start)

print('wrong_bars with', wrong_bars['AAPL'][0].t)
#  The current date is printed

print('correct_bars with', correct_bars['AAPL'][0].t)
# correct date is printed, 2016-01-04 09:25:00-05:00
```

Relatedly, calling `get_barset()` and specifying `start` but not `limit` is substantially slower.

**Comment by shlomikushchi** [comment]
Hi, Look at the README file of the project to see how to correctly use get_barset()

**Comment by cechmanek** [comment]
Hi. I've read this package README and the docs at https://alpaca.markets/docs/api-documentation/api-v2/market-data/bars/
Neither indicate that I can't combine `limit` and `start` arguments.

The example shown in the README doesn't specify a value for `limit`.

I think this issue is real. I don't see why manually setting `limit=100`, which is the stated default value anyway, should change the time range of bars returns.

**Comment by shlomikushchi** [comment]
The issue is that the Limit (if specified) is taken from the end date. 
When you don't specify an end date, the default value is now
you could instead do something like this: 
```py
import pandas as pd
import datetime

limit = 100
NY = 'America/New_York'

end_date = pd.Timestamp('2016-01-01', tz=NY)

api.get_barset('AAPL', '5Min', end=end_date.isoformat(), limit=limit).df
```

you will get:

![image](https://user-images.githubusercontent.com/7924802/99882084-98457400-2c26-11eb-80f1-241c4135203d.png)

**Comment by shlomikushchi** [comment]
Also, if you still have a performance issue - just making sure that you know 

You could get data for up to 200 stocks with one api call by specifying a list.
If that can help and you need a code example let me know

**Comment by cechmanek** [comment]
>"The issue is that the Limit (if specified) is taken from the end date."
>
This explains a lot. I can modify my code with this in mind.

Can I ask that this be pointed out more prominently in the docs?

**Comment by shlomikushchi** [comment]
Hi, this PR adds this note: https://github.com/alpacahq/alpaca-trade-api-python/pull/326/

**Comment by cechmanek** [comment]
> Hi, this PR adds this note: #326

That's great. Thank you.
