### ISSUE TITLE
trade_updates stream returns 'invalid symbol'

### ISSUE THREAD

**Issue by nlusskin** [alpacahq/alpaca-trade-api-python#337]
![image](https://user-images.githubusercontent.com/2939846/102101580-cf0f4400-3df8-11eb-9ab7-f0e3fa890ca3.png)

Using the exact syntax from this repo README. Returns the above error when connecting directly via websocket. StreamConn api throws an event loop error
`ERROR:root:error while consuming ws messages: Error while connecting to wss://data.alpaca.markets/stream:your connection is rejected while another connection is open under the same account`

**Comment by shlomikushchi** [comment]
Hi, it seems you are using an old version of the package? you are not supposed to use `polyfeed/trade_updates` for the subscription. take a look at this example to learn how to do it, and make sure you use the latest code base: https://github.com/alpacahq/alpaca-trade-api-python/blob/master/examples/websocket_example.py

**Comment by KyleStevenYoung** [comment]
shlomikushchi  - simply to add more depth to the issue; nlusskin is using mscat via terminal to query the alpaca api and not using the SDK specifically. The example he is following is located on Alpaca's website and i have verified that the trade_updates portion does not function as he described. 
alpaca link: https://alpaca.markets/docs/api-documentation/api-v2/streaming/

**Comment by drew887** [comment]
Hey closing this one out due to inactivity
