### ISSUE TITLE
polygon daily open close returns a 403

### ISSUE THREAD

**Issue by tjquinn1** [alpacahq/alpaca-trade-api-python#354]
When I try to access daily open close data from polygon it returns a 403. I am using live credentials and am able to access other polgyon endpoints such as historic aggs. I have checked the URLs and they seem correct. 

I try:
api.polygon.daily_open_close('TICK', '2020/01/04')

`403 Client Error: Forbidden for url: https://api.polygon.io/v1/open-close/FCEL/2020/01/04?apiKey=*****************************`

When I hit the endpoint in the browser it returns:

```
{
status: "NOT_AUTHORIZED",
request_id: "69ee041d94e67ebaffc03ac5c64cfcb8",
message: "You are not entitled to this data. Please upgrade your plan at https://polygon.io/pricing"
}

```
I am not sure what other data I can provide but if anything else could be useful, I am happy to supply it. Maybe this is an issue to take up with polygon? From what I understand a live alpaca account includes all the polygon stock endpoints correct?

**Comment by shlomikushchi** [comment]
Hi, your date format is wrong.
![image](https://user-images.githubusercontent.com/7924802/104013970-eb658d00-51ba-11eb-8c30-cf7032dd167b.png)

**Comment by drew887** [comment]
Hey closing this one out due to inactivity
