### ISSUE TITLE
Bracket order improvements

### ISSUE THREAD

**Issue by algonell** [alpacahq/alpaca-trade-api-python#357]
Allow custom time in force for parent order and brackets:
    1. Currently if order is 'day' and filled, there will be no brackets the next day. 
    2. If order is 'gtc' and unfilled we will have to cancel it before close.

**Comment by shlomikushchi** [comment]
Hi, this is the sdk (client) side. open your feature request here: https://forum.alpaca.markets/c/alpaca/feature-requests/14

**Comment by algonell** [comment]
kk
