### ISSUE TITLE
historic_agg_v2 returns data before the stock was even listed

### ISSUE THREAD

**Issue by melgazar9** [alpacahq/alpaca-trade-api-python#361]
NIO released its IPO on September 12, 2018, yet somehow data is returned since 2003-10-01. What concerns me more is there is no missing data in any of these rows, so how is this data being populated?

```
import alpaca_trade_api as alpaca_api
nio = alpaca_api.REST(**ALPACA_HEADERS).polygon.historic_agg_v2('AAPL', 1, 'day', _from='1900-01-01', to='2099-12-31').df # returns data since 2003

nio.index.min()
Out[8]: Timestamp('2003-10-01 00:00:00-0400', tz='America/New_York')

nio.index.to_series().diff().max()
Out[23]: Timedelta('887 days 00:00:00')

```

I also looked at AAPL as an example since it's popular.  AAPL released their IPO on December 12, 1980, so that makes sense that AAPL only returns data from 2003-10-01 as well.  It looks like there is a filter that min datetime is 2003? This definitely looks like a bug with NIO. If this is the case with NIO, how many other bugs are there? How can I trust any of the other tick data if even one single symbol returns the wrong information?

**Comment by drew887** [comment]
Hey closing this one out due to inactivity and that polygon has been removed. Please re-open if this is still happening with the alpaca market data apis
