### ISSUE TITLE
Using paper trading, bars request returns 403 Forbidden

### ISSUE THREAD

**Issue by joshterrill** [alpacahq/alpaca-trade-api-python#367]
I've been running paper trading for the last few days without problem. Today for some reason, when I go to look up prices using the bars API, I am getting a 403 forbidden error.

I have version 0.51.0 installed, which from what I can tell on pip, is thee latest version.

Here's a simple example.

```python
import alpaca_trade_api as tradeapi

api = tradeapi.REST(base_url="https://paper-api.alpaca.markets", key_id="<my paper key here>", secret_key="<my paper secret here>")

def get_current_price(ticker):
    symbol_bars = api.get_barset(ticker, 'minute', 1).df.iloc[0]
    current_price = symbol_bars[ticker]['close']
    return float(current_price)

print(get_current_price("AAPL"))
```

This code example is almost straight from the API documentation.

The error I get is:

```
Traceback (most recent call last):
  File "trader.py", line 110, in <module>
    print(get_current_price("AAPL"))
  File "trader.py", line 94, in get_current_price
    symbol_bars = api.get_barset(ticker, 'minute', 1).df.iloc[0]
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 456, in get_barset
    resp = self.data_get('/bars/{}'.format(timeframe), params)
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 172, in data_get
    return self._request(
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 119, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 140, in _one_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://data.alpaca.markets/v1/bars/minute?symbols=AAPL&limit=1
```

This code has been working without problem until this morning, for some reason. 

Edit: I've also tried forcing the version in the constructor of the trade API to be `v2`, however, looking at the documentation here: https://alpaca.markets/docs/api-documentation/api-v2/market-data/bars/ it appears that the v2 API still uses a v1 URL for this action?

**Comment by joshterrill** [comment]
What's strange is all of the other methods for getting account balance, orders, etc. appear to work. I just tried regenerating my API keys, and it appeared to fix this problem. I'm not sure if I should leave this ticket open or closed. I guess I can close it for now.

**Comment by impulsecorp** [comment]
I had the same problem today. My paper trading strategies were working fine up until today when they started giving the "403 Client Error: Forbidden for url" error.  As you suggested, and I regenerated my API keys and that fixed it.
