### ISSUE TITLE
`financials_v2` returns error `AttributeError: 'REST' object has no attribute 'financials_v2'`

### ISSUE THREAD

**Issue by ItsJamesMurray** [alpacahq/alpaca-trade-api-python#374]
Hello!

Running a simple example to get `AAPL` financials returns an error.

Expected Result:  Financial Data for AAPL

Actual Result: `AttributeError: 'REST' object has no attribute 'financials_v2'`

Sample Code:

```python
import alpaca_trade_api as tradeapi

api = tradeapi.REST(API_KEY, SECRET_KEY, base_url=BASE_URL)
print(api.polygon.financials_v2(symbol='AAPL', limit=5, report_type='Y'))
```

**Comment by ItsJamesMurray** [comment]
I will note, that running `print(api.polygon.financials(symbol='AAPL'))` works, however that is not reflected in the docs and it does not include the additional variables in the polygon V2 api.

**Comment by shlomikushchi** [comment]
Hi, what version of alpaca_trade_api to you have installed?

**Comment by ItsJamesMurray** [comment]
Version: 0.51.0

**Comment by shlomikushchi** [comment]
upgrade to 0.52.0 (it was released in 52)

**Comment by ItsJamesMurray** [comment]
That worked!  Thanks!

Only thing I'd note is the documentation here is a bit lacking for this call.

I had to import `from alpaca_trade_api.polygon.rest import FinancialsReportType, FinancialsSort` and rather than using a string input for the `report_type` and `sort` as expected, I had ot use `FinancialReportType` and `FinancialsSort`.

```python
import alpaca_trade_api as tradeapi
from alpaca_trade_api.polygon.rest import FinancialsReportType, FinancialsSort

api = tradeapi.REST(API_KEY, SECRET_KEY, base_url=BASE_URL)

print(api.polygon.financials_v2('AAPL', 5, FinancialsReportType.Y, FinancialsSort.ReportPeriodDesc))
```

**Comment by shlomikushchi** [comment]
using strings is error prone. using enums will avoid this.

**Comment by drew887** [comment]
Hey closing this one out due to inactivity
