### ISSUE TITLE
pip install fails on Apple M1 Silicon Big Sur 11.1 

### ISSUE THREAD

**Issue by connerlane** [alpacahq/alpaca-trade-api-python#380]
[output.txt](https://github.com/alpacahq/alpaca-trade-api-python/files/5955844/output.txt)
seems to be because of numpy version

**Comment by connerlane** [comment]
actually, sorry, it seems to be because of pandas

**Comment by SeltzerFish** [comment]
Workaround: https://alexslobodnik.medium.com/apple-m1-python-pandas-and-homebrew-20f14828ccc7
