### ISSUE TITLE
get_last_quote(), get_last_trade() support multiple symbols?

### ISSUE THREAD

**Issue by waynexuto** [alpacahq/alpaca-trade-api-python#387]
Possibility to support multiple symbols query in one REST request via get_last_quote() and get_last_trade()?

**Comment by gnvk** [comment]
At this time the only "latest" endpoint that does support multiple symbols is `get_snapshots`. It returns the latest trade, quote, minute bar, daily bar and previous daily bar for all the queried symbols. It's possible, that multi-symbol latest trade/quote endpoints will be added in the future. Until then, I recommend you use the snapshots.
