### ISSUE TITLE
Get Bars does not work

### ISSUE THREAD

**Issue by drbh** [alpacahq/alpaca-trade-api-python#393]
```python
import alpaca_trade_api as tradeapi
from alpaca_trade_api.rest import TimeFrame

API_KEY = "XXXXXXXXX"
API_SECRET = "XXXXXXXXX"

api = tradeapi.REST(
  key_id=API_KEY,
  secret_key=API_SECRET,
  api_version='v2',
  base_url='https://paper-api.alpaca.markets'
)

api.get_bars(
  symbol='AAPL',
  timeframe=TimeFrame.Minute,
  start="2019-04-15T09:30:00-04:00", 
  end="2019-04-16T09:30:00-04:00", 
  limit=10, 
)

# requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://data.alpaca.markets/v2/stocks/AAPL/bars?timeframe=1Min&adjustment=all&start=2019-04-15T09%3A30%3A00-04%3A00&end=2019-04-16T09%3A30%3A00-04%3A00&limit=10
```

I can't seem to figure out how to make this work..

Also the `base_url` in the `REST` class does not seem to impact the url in the error. This issue seems related to https://github.com/alpacahq/Alpaca-API/issues/77 but I could not find instructions that would enable me to fetch 1 minute bars

**Comment by SDiamante13** [comment]
The error seems to indicate that your credentials (API_KEY and SECRET_KEY) are incorrect. I copied your code and ran it with my credentials and it returns the data just fine. 

The `base_url` defaults to live trading so it would effect which endpoint it hits.

**Comment by drbh** [comment]
@SDiamante13 thanks!

**Comment by bourba85** [comment]
Hi,

I am experiencing the same issue ("403 Client Error: Forbidden for url:") but I verified that both my API_KEY and SECRET_KEY are correct and that the environment variables have also been set correctly. Any help would be greatly appreciated! Thanks
