### ISSUE TITLE
"end is too late for subscription" Error

### ISSUE THREAD

**Issue by amor71** [alpacahq/alpaca-trade-api-python#394]
When calling `get_bars()` with `now()` while the market is closed HTTP Error 422 is returned w/ `end is too late for subscription`.  The expected behavior is to pull data till the last available date entry if the end date is in the future.

**Comment by crawforc3** [comment]
What's the correct way to get bars for the current day?

Using:
`api.get_bars('AAPL', timeframe=TimeFrame.Minute, start=dt.date.today(), end=dt.date.today())`

I'm getting this error: `alpaca_trade_api.rest.APIError: end is too late for subscription (edite`

**Comment by vecn** [comment]
I got this error too, 

After some reading I found in [documentation of public beta status](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#public-beta-status) following statement:

> "...users with Free subscription will receive an error when trying to access data that is too recent."

**Comment by haxdds** [comment]
Historical market data is limited for free data plans. Free accounts cannot request historical data within the last 15 minutes. If you want to receive recent market data, you must do it through the streaming interface.

Learn more about market data subscriptions here:

https://alpaca.markets/data

https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/
