### ISSUE TITLE
martingale example error "stream" not defined

### ISSUE THREAD

**Issue by jabowery** [alpacahq/alpaca-trade-api-python#397]
'stream' is used but is nowhere defined in the `martingale.py` example.

Nick Johnson pointed this out 9 days ago and his suggested fix `(:%s/stream\./conn./g)` works:

https://github.com/alpacahq/alpaca-trade-api-python/commit/9283a06f87cc9bb80832c1d6f94773eed186e6f5#r47750401

**Comment by gnvk** [comment]
Fixed by https://github.com/alpacahq/alpaca-trade-api-python/pull/461
