### ISSUE TITLE
 APIError: access key verification failed 

### ISSUE THREAD

**Issue by real-quantdog** [alpacahq/alpaca-trade-api-python#40]
Hello, 

I am new to using APIs and I am trying to connect to the API. 

I am doing the following steps on Windows 7.

1) pip3 install alpaca-trade-api

I install this to the folder with my anaconda packages. I am on Python 3.6.3

2) I am running the anaconda prompt to run the Curl function. I remove the '\' because I am on windows. 

curl -X GET -H "APCA-API-KEY-ID: NOTTHECODET70" -H "APCA-API-SECRET-KEY: I6/NOTTHECODECKNOTTHECODE" https://api.alpaca.markets/v1/account

I get this from the following link : 
https://docs.alpaca.markets/web-api/

3) I go back into Python I run the following code.

import alpaca_trade_api as tradeapi
api = tradeapi.REST('NOTTHECODE', 'NOTTHECODENOTTHECODENOTTHECODE')
api.get_account()

I am given the following response. 

APIError: access key verification failed : access key not found (Code = 40110000) (Code = 40110000)

I am not sure what I have to do. I appreciate the help. 

Thank you, 

Eric

**Comment by umitanuki** [comment]
The code looks fine so it's likely the key you are specifying might be wrong.

You can check the actual HTTP header by adding this before the code.

```

# You must initialize logging, otherwise you'll not see debug output.
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True
```

**Comment by SaviourSelf** [comment]
I'm experiencing a similar issue. Yesterday I was able to generate a key and get this working after trading hours. This morning, I tried using the same key from yesterday and I'm getting:

alpaca_trade_api.rest.APIError: access key verification failed : request is unauthorized (generate APCA-API-KEY-ID and APCA-API-ACCESS-SECRET-KEY from dashboard and include in HTTP header) (Code = 40110000) (Code = 40110000)

I generated a new key, and I was able to get passed this error.

**Comment by umitanuki** [comment]
Your curl example is pointing to paper-api while your python example is to live trading. You can give `https://paper-apip.alpaca.markets/` to the third argument of `REST()`

**Comment by real-quantdog** [comment]
Thank you for all your help! The solution was very simple. I realized the curl function did not have to be used with python. Then all I had to do was add the url to the paper trading account. 


api = tradeapi.REST('PK53RZXVSO70ZWANC27Q', 'TOCuoIpJdxPCDi1txOStLsxW4DpdBMm4N3kkdAv7' , 'https://paper-api.alpaca.markets')

**Comment by cgi1** [comment]
> Your curl example is pointing to paper-api while your python example is to live trading. You can give `https://paper-apip.alpaca.markets/` to the third argument of `REST()`

`https://paper-api.alpaca.markets/` without typo
