### ISSUE TITLE
Get Bars does not return data

### ISSUE THREAD

**Issue by ElliotVilhelm** [alpacahq/alpaca-trade-api-python#402]
Hi, perhaps this is because of v2 being in beta, if so makes sense. Although, I have confirmed the same issue on the v1 endpoint.

```python
BASE_URL = URL('https://api.alpaca.markets')
ALPACA_API_KEY = 'xx'
ALPACA_SECRET_KEY ='xx'

api = alpaca.REST(key_id=ALPACA_API_KEY,
                  secret_key=ALPACA_SECRET_KEY,
                  base_url=BASE_URL)
now = pd.Timestamp.now(tz='America/New_York').floor('1min')
yesterday = (now - pd.Timedelta('1day')).strftime('%Y-%m-%d')
today = now.strftime('%Y-%m-%d')
tomorrow = (now + pd.Timedelta('1day')).strftime('%Y-%m-%d')

data = api.get_bars(symbol, TimeFrame.Hour, yesterday, today, adjustment='raw').df
print(f'{yesterday} - {today}')
print(data)
```

```
❯ python test.py
2021-03-17 - 2021-03-18
Empty DataFrame
Columns: []
Index: []
```

`get_bars` returns an empty dataframe, I have tried various days and have tired different time frames and have the same issue. Some older random time intervals with some random time frames do occasionally work.

I did see this photo in the docs V2 api: https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/
<img width="730" alt="Screen Shot 2021-03-18 at 1 33 18 PM" src="https://user-images.githubusercontent.com/22024236/111693973-821f7d00-87ee-11eb-9661-b42743d28026.png">

Is this regarding V1 api as well? I tested this feature with the v1 endpoint using
```python
BASE_URL = 'https://data.alpaca.markets/v1'
```

Same output.

**Comment by ElliotVilhelm** [comment]
FYI to those struggling with the same issue it seems the deprecated `get_barset` is working on recent data
```python
today = now.strftime('%Y-%m-%d')
tomorrow = (now + pd.Timedelta('1day')).strftime('%Y-%m-%d')
data = api.get_barset(['AAPL'], 'minute', start=today, end=tomorrow).df
print(data)
```

```
❯ python test.py
                              AAPL
                              open     high      low   close volume
time
2021-03-18 14:20:00-04:00  121.700  121.785  121.710  121.78   2017
2021-03-18 14:21:00-04:00  121.810  121.810  121.635  121.67   4519
2021-03-18 14:22:00-04:00  121.680  121.690  121.650  121.66   2590
2021-03-18 14:23:00-04:00  121.645  121.660  121.640  121.66   1942
2021-03-18 14:24:00-04:00  121.660  121.645  121.630  121.64   1849
...                            ...      ...      ...     ...    ...
2021-03-18 15:55:00-04:00  120.510  120.740  120.485  120.66  19791
2021-03-18 15:56:00-04:00  120.655  120.760  120.640  120.74  21741
2021-03-18 15:57:00-04:00  120.745  120.765  120.660  120.66  13177
2021-03-18 15:58:00-04:00  120.660  120.700  120.530  120.70  22958
2021-03-18 15:59:00-04:00  120.710  120.740  120.545  120.56  22222

[100 rows x 5 columns]
```

**Comment by gnvk** [comment]
Please check this again on the latest version. If it's working, close the issue, if not, comment the problem. Thanks!

**Comment by ElliotVilhelm** [comment]
I am no longer using Alpaca.

**Comment by HeyWY1** [comment]
epic lol

**Comment by AbhayPrajapati195** [comment]
update this is not working in the new version.

**Comment by gnvk** [comment]
> update this is not working in the new version.

What is not working?

**Comment by AbhayPrajapati195** [comment]
> > update this is not working in the new version.
> 
> What is not working?

get_barset is not available in the latest version of the python api. and get_bars is returning an empty array.

**Comment by gnvk** [comment]
> get_bars is returning an empty array.

With which parameters?

**Comment by AbhayPrajapati195** [comment]
> > get_bars is returning an empty array.
> 
> With which parameters?

my bad, got the timeframe parameter wrong.

**Comment by bable631** [comment]
This is now happening to me. Exact same issue. It was working less than a week ago, I changed nothing, and now I get no data at all.

**Comment by SaroLovito** [comment]
As gnvk was saying, when the market is closed you will receive null. So I'll suggest you to provide "start" & "end" parameter in timestamp format -> e.g.:

symbol = 'AA'
historical_data = api.get_bars(symbol, '1Min', limit=5, start="2018-01-01T00:00:00-00:00",
    end="2018-02-01T00:00:00-00:00").df
print(historical_data)

I hope this will help you

**Comment by andyllerena** [comment]
> > > update this is not working in the new version.
> > 
> > 
> > What is not working?
> 
> get_barset is not available in the latest version of the python api. and get_bars is returning an empty array.

were you able to figure it out?
