### ISSUE TITLE
Fractional Share Support

### ISSUE THREAD

**Issue by priten1** [alpacahq/alpaca-trade-api-python#404]
Is there an ETA on when this sdk will support fractional shares?

https://alpaca.markets/learn/fractional-shares-api/

**Comment by mscully4** [comment]
This can be done fairly easily using the package as it currently exists

`def put_fractional_order(api, symbol: str, notional: float, side: str):
    side = side.lower()
    symbol = symbol.upper()

    assert side.lower() in ['buy', 'sell']
    assert notional > 0

    data = {
            "symbol": symbol,
            "notional": notional,
            "side": side,
            "type": "market",
            "time_in_force": "day"
        }

    try:  
        api._request('POST', '/orders', data=data)
        logging.info(f"Placed order for ${notional} of {symbol}")
    except Exception as e:
        logging.error(f"{e} ({symbol})")`

**Comment by Gillinghammer** [comment]
@mscully4 Using the notional key and your function is not working for me. 
Error says `qty is required` still

Has anyone got fractional shares working yet?

**Comment by camelpac** [comment]
Hi, you could use it like this:
```py
api.submit_order("AAPL", "1.5", "buy", type="market",time_in_force="day",)
```

results in:
![image](https://user-images.githubusercontent.com/78740792/112736687-9dfcee80-8f65-11eb-888c-8ec42f96a744.png)

**Comment by priten1** [comment]
Sorry about the late reply on this.

100% agree it's extremely easy to make a simple function to implement the feature in your own projects (which is what I've done), but shouldn't this be added into the python sdk natively?

**Comment by mscully4** [comment]
@priten1 Agree that it should be added to the SDK.  The troublesome thing is that the submit_order function would have to have its args changed so that quantity is no longer required and the user could specify either a quantity or notional amount.  Changing the function args would break code that people have already written.  Or a new method solely for fractional trading would have to be created.

**Comment by priten1** [comment]
Yea, I can see that. An option could be to add a new argument called order_type that defaults to "shares". If that's set to "value" or "dollars" the method could send in a notional call.

**Comment by bfan1256** [comment]
Looks like even @mscully4 code doesn't work anymore...
