### ISSUE TITLE
Invalid TimeFrame in getbars for hourly

### ISSUE THREAD

**Issue by hansonkd** [alpacahq/alpaca-trade-api-python#409]
Hello when I try to use the example, I get an error:

`api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df`

```
"""
Traceback (most recent call last):
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 160, in _one_request
    resp.raise_for_status()
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v2/stocks/AAPL/bars?timeframe=1Hour&adjustment=raw&start=2021-02-08&end=2021-02-08&limit=10

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_hourly.py", line 231, in make_df
    tdf = api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 625, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 611, in get_bars_iter
    for bar in bars:
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 535, in _data_get_v2
    resp = self.data_get('/stocks/{}/{}'.format(symbol, endpoint),
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 192, in data_get
    return self._request(
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 139, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 168, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: invalid timeframe
```

Minute data seems to work.

**Comment by Codered315** [comment]
I also get a similar error:
`Exception in thread Thread-5:     
Traceback (most recent call last):
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python37-32\lib\site-packages\alpaca_trade_api\rest.py", line 160, in _one_request 
    resp.raise_for_status()
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 943, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v2/stocks/%5B'SPY',%200%5D/bars?timeframe=1Min&adjustment=raw&start=2021-03-30&end=2021-03-30&limit=10`

Also "pd" in the long-short.py example file is not defined, you need:
`import pandas as pd`

**Comment by dgabriele** [comment]
Same here. Minute and Daily time frames work. **Hourly** TimeFrame results in an API error with `invalid timeframe`. Any update on this? The example in the docs doesn't work. The `get_bars` call for hourly APPL data.

**Comment by doctorcolossus** [comment]
Same.

**Comment by SDiamante13** [comment]
I have opened an issue in the API issue tracker. It seems to be a problem with the API itself rather than the SDK. You can follow up that as well. [Issue #178](https://github.com/alpacahq/Alpaca-API/issues/178)

**Comment by crawforc3** [comment]
No updates still?

**Comment by camelpac** [comment]
Hi guys, sorry for late response. please make sure you are using the latest version of the sdk (right now 1.2.3). and try this example code: 
```py
from alpaca_trade_api.rest import TimeFrame 
api.get_bars("AAPL", TimeFrame.Hour, "2021-06-01", "2021-06-01").df.iloc[:10]
```
it will result in: 

![image](https://user-images.githubusercontent.com/78740792/124254660-f548c700-db31-11eb-9103-3adeb9302b1f.png)

**Comment by camelpac** [comment]
closing the issue. let me know if there are still problems.

**Comment by Bittybaby2025** [comment]
anyone have errors. i am getting alpaca errors for timeframe for 5minute bars:

rom alpaca.data.timeframe import TimeFrame, TimeFrameUnit

from alpaca.data.enums import DataFeed, Adjustment

import alpaca_trade_api as alpacaapi

from alpaca.data.historical import StockHistoricalDataClient

from alpaca.data.requests import StockBarsRequest, StockLatestTradeRequest

import requests

API_KEY = os.getenv(“ALPACA_API_KEY”)

API_SECRET = os.getenv(“ALPACA_API_SECRET_KEY”)

BASE_URL = “https://paper-api.alpaca.markets/”

data_client = StockHistoricalDataClient(API_KEY, API_SECRET)

#data_client = StockHistoricalDataClient(API_KEY, API_SECRET, feed=“iex”)

api = REST(API_KEY, API_SECRET, base_url=BASE_URL)

logger = logging.getLogger(name)
timeframe=TimeFrame(5, TimeFrameUnit.Minute) # if you’re using new Alpaca SDK and this format

trying to use indicators in my get indicators function and it it throwing error:

my class in get indicators:

request = StockBarsRequest(
symbol_or_symbols=symbol,
timeframe=TimeFrame(5, TimeFrameUnit.Minute),
start=start,
end=end,
feed=“iex”
)
bars = data_client.get_stock_bars(request).df

server is throwing this error:

WARNING:root:Failed to get indicators for OMEX: 1 validation error for StockBarsRequest
timeframe
Input should be an instance of TimeFrame [type=is_instance_of, input_value=<alpaca_trade_api.rest.Ti…e object at 0x10557a8d0>, input_type=TimeFrame]
For further information visit [Redirecting...](https://errors.pydantic.dev/2.11/v/is_instance_of)
WARNING:root:Failed to get indicators for PAVMZ: 1 validation error for StockBarsRequest
timeframe

I am trying to dynamically get top mover from the alpaca top mover and iterate through it for automated tradingf: WORKED fabuluslously woohoo!

now i need to include an indicator strategy for precise entry and exit signals all the code in for indicators but, timeframe error is blocking my trades PLEASE HELP me. i am almost there

**Comment by Bittybaby2025** [comment]
> Hello when I try to use the example, I get an error:
> 
> `api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df`
> 
> ```
> """
> Traceback (most recent call last):
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 160, in _one_request
>     resp.raise_for_status()
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v2/stocks/AAPL/bars?timeframe=1Hour&adjustment=raw&start=2021-02-08&end=2021-02-08&limit=10
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "run_hourly.py", line 231, in make_df
>     tdf = api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 625, in get_bars
>     bars = list(self.get_bars_iter(symbol,
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 611, in get_bars_iter
>     for bar in bars:
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 535, in _data_get_v2
>     resp = self.data_get('/stocks/{}/{}'.format(symbol, endpoint),
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 192, in data_get
>     return self._request(
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 139, in _request
>     return self._one_request(method, url, opts, retry)
>   File "/home/kyle/.virtualenv/lib/python3.8/site-packages/alpaca_trade_api/rest.py", line 168, in _one_request
>     raise APIError(error, http_error)
> alpaca_trade_api.rest.APIError: invalid timeframe
> ```
> 
> Minute data seems to work.

5 minute dat is not working for me. plese help
