### ISSUE TITLE
adjustment=raw is ignored in `get_bars_iter`

### ISSUE THREAD

**Issue by dgabriele** [alpacahq/alpaca-trade-api-python#413]
`get_bars_iter` returns `Bar` objects, even when `adjustment='raw'` kwarg set. Plain `dict` objects expected.

**Comment by camelpac** [comment]
Hi, what you are looking for is `_raw`. something like this:
`api.get_bars("AAPL", TimeFrame.Hour, "2021-06-01", "2021-06-01")._raw`

this will result in raw data : 
![image](https://user-images.githubusercontent.com/78740792/124254089-6340be80-db31-11eb-89db-64a912ffff34.png)

**Comment by gnvk** [comment]
@dgabriele I cannot reproduce this:
```python
>>> list(a.get_bars_iter('AAPL', "1Hour", start='2021-09-29', limit=3, raw=True))
[{'t': '2021-09-29T08:00:00Z', 'o': 143.6, 'h': 143.94, 'l': 143.22, 'c': 143.57, 'v': 70200, 'n': 1223, 'vw': 143.55515},
{'t': '2021-09-29T09:00:00Z', 'o': 143.6, 'h': 143.63, 'l': 143.27, 'c': 143.6, 'v': 19835, 'n': 470, 'vw': 143.503788},
{'t': '2021-09-29T10:00:00Z', 'o': 143.6, 'h': 143.68, 'l': 143.3, 'c': 143.3, 'v': 19161, 'n': 476, 'vw': 143.561808}]
```

Please clarify!
