### ISSUE TITLE
EntityV2 convert function throws error at Object.fromEntries

### ISSUE THREAD

**Issue by csidi90** [alpacahq/alpaca-trade-api-python#414]
I dont know why, but the latest code in EntityV2 within the convert function has this code which doesnt work and needs to be changed.

`function convert(data, mapping) {
  const obj = Object.fromEntries(
    Object.entries(data).map(([key, val]) => [
      mapping.hasOwnProperty(key) ? mapping[key] : key,
      val,
    ])
  );
  return obj;
}`

Object.fromEntries isnt a function, it needs to be set to Object.entries, please fix this issue so I can go live with my alpaca apps again.

**Comment by camelpac** [comment]
Hi, this is the python sdk. please open your issue (if still exists in the js-sdk: https://github.com/alpacahq/alpaca-trade-api-js)
