### ISSUE TITLE
TimeFrame.Hours 

### ISSUE THREAD

**Issue by FarhanQ7** [alpacahq/alpaca-trade-api-python#417]
**Code from documentation:**

``` from alpaca_trade_api.rest import REST
api = REST()

api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df ```


Returns the Error:

Traceback (most recent call last):
  File "trade_bot.py", line 18, in <module>
    api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df
AttributeError: type object 'TimeFrame' has no attribute 'Hour'

**Comment by mckornfield** [comment]
have you tried `from alpaca_trade_api.rest import REST, TimeFrame` ?

**Comment by cozywind2010** [comment]
or add those:

from enum import Enum

class TimeFrame(Enum):
    Day = "1Day"
    Hour = "1Hour"
    Minute = "1Min"
    Sec = "1Sec"

**Comment by FarhanQ7** [comment]
> have you tried `from alpaca_trade_api.rest import REST, TimeFrame` ?

Tried it, no luck

**Comment by FarhanQ7** [comment]
> or add those:
> 
> from enum import Enum
> 
> class TimeFrame(Enum):
> Day = "1Day"
> Hour = "1Hour"
> Minute = "1Min"
> Sec = "1Sec"

Seems to be something wrong with the way the Alpaca API deals with TimeFrame

**Comment by crawforc3** [comment]
Even though Hours was used in the documentation example, it wasn't actually available from Alpaca. But it looks like Alpaca's recent update included Hour bars.

**Comment by Remcat** [comment]
this:
`api.get_bars("AAPL",` tradeapi.TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=1000, adjustment='raw').df`
should be:
`api.get_bars("AAPL", tradeapi.rest.TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=1000, adjustment='raw').df`

**Comment by camelpac** [comment]
Hi guys, 
are you using the latest version? 
I just ran this:
![image](https://user-images.githubusercontent.com/78740792/121699634-c9f52e00-cad7-11eb-994b-3287c32c3d5e.png)

**Comment by Remcat** [comment]
@camelpac , the documenation doesn't mention the need to `import TimeFrame`, fyi.

**Comment by problemss** [comment]
I imported the alpaca_trade_api as tradeapi and then just called it like this,

`tradeapi.rest.TimeFrame.Hour`

**Comment by kzhdev** [comment]
I got following error
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~\miniconda3\envs\alpaca\lib\site-packages\alpaca_trade_api\rest.py in _one_request(self, method, url, opts, retry)
    160         try:
--> 161             resp.raise_for_status()
    162         except HTTPError as http_error:

~\miniconda3\envs\alpaca\lib\site-packages\requests\models.py in raise_for_status(self)
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 

HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v2/stocks/AAPL/bars?timeframe=1Hour&adjustment=raw&start=2021-02-08&end=2021-02-08&limit=10

During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
<ipython-input-13-504d8904cb42> in <module>
      1 from alpaca_trade_api.rest import REST, TimeFrame
      2 api = REST()
----> 3 api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df

~\miniconda3\envs\alpaca\lib\site-packages\alpaca_trade_api\rest.py in get_bars(self, symbol, timeframe, start, end, adjustment, limit)
    629                  limit: int = None,
    630                  ) -> BarsV2:
--> 631         bars = list(self.get_bars_iter(symbol,
    632                                        timeframe,
    633                                        start,

~\miniconda3\envs\alpaca\lib\site-packages\alpaca_trade_api\rest.py in get_bars_iter(self, symbol, timeframe, start, end, adjustment, limit, raw)
    615                                  adjustment=adjustment,
    616                                  start=start, end=end, limit=limit)
--> 617         for bar in bars:
    618             if raw:
    619                 yield bar

~\miniconda3\envs\alpaca\lib\site-packages\alpaca_trade_api\rest.py in _data_get_v2(self, endpoint, symbol, **kwargs)
    539             data['limit'] = actual_limit
    540             data['page_token'] = page_token
--> 541             resp = self.data_get('/stocks/{}/{}'.format(symbol, endpoint),
    542                                  data=data, api_version='v2')
    543             items = resp.get(endpoint, [])

~\miniconda3\envs\alpaca\lib\site-packages\alpaca_trade_api\rest.py in data_get(self, path, data, api_version)
    191     def data_get(self, path, data=None, api_version='v1'):
    192         base_url: URL = get_data_url()
--> 193         return self._request(
    194             'GET', path, data, base_url=base_url, api_version=api_version,
    195         )

~\miniconda3\envs\alpaca\lib\site-packages\alpaca_trade_api\rest.py in _request(self, method, path, data, base_url, api_version)
    138         while retry >= 0:
    139             try:
--> 140                 return self._one_request(method, url, opts, retry)
    141             except RetryException:
    142                 retry_wait = self._retry_wait

~\miniconda3\envs\alpaca\lib\site-packages\alpaca_trade_api\rest.py in _one_request(self, method, url, opts, retry)
    167                 error = resp.json()
    168                 if 'code' in error:
--> 169                     raise APIError(error, http_error)
    170             else:
    171                 raise

APIError: limit must be large enough to compute an aggregate bar
```

**Comment by kzhdev** [comment]
Only Hour not work. Minute and Day works fine.

**Comment by kzhdev** [comment]
> Hi guys,
> are you using the latest version?
> I just ran this:
> ![image](https://user-images.githubusercontent.com/78740792/121699634-c9f52e00-cad7-11eb-994b-3287c32c3d5e.png)

Why it returns a bar in 2021-02-09? This is not right. If I set limit=10, it should return 10 bars, right?

**Comment by camelpac** [comment]
@kzhdev setting a low limit results in calculation error. easiest thing for you to do would be filtering the data you receive. 
for instance if you want 10 sample you could do this:  
```py
api.get_bars("AAPL", TimeFrame.Hour, "2021-06-01", "2021-06-01").df.iloc[:10]
```
![image](https://user-images.githubusercontent.com/78740792/124253081-5374aa80-db30-11eb-948c-e3f7a2de8b38.png)

or this:

![image](https://user-images.githubusercontent.com/78740792/124253132-625b5d00-db30-11eb-8fe3-56f3c77d5b0b.png)

**Comment by kzhdev** [comment]
@camelpac Thanks for you response. 

I believe this is a bug in backend. The "limit must be large enough to compute an aggregate bar" API error is returned from backend. 

According to API doc, **"- limit. Number of data points to return. Must be in range 1-10000, defaults to 1000."**, If I give a limit 10, I'm expecting the backend returns 10 hourly bars (or less if there is less than 10 bars in that day).  According the error, I'm feeling the backend applied the limit to how many data used not on the result.

**Comment by camelpac** [comment]
@kzhdev this might be an issue. Just remember that this is an sdk client. it's the backend implementation. 
You should try ask about this in the slack chat or the alpaca forum.

**Comment by gnvk** [comment]
@kzhdev limit=10 now does return 10 bars, regardless of the timeframe. I'm closing this.
