### ISSUE TITLE
Rounding error occurs with buying power

### ISSUE THREAD

**Issue by dewball345** [alpacahq/alpaca-trade-api-python#419]
Hi there,

When trying out your paper trading API I had trouble making transactions because there was a rounding error with the buying power

![image](https://user-images.githubusercontent.com/30184788/115275962-50544b80-a0f7-11eb-960b-7bb86871247a.png)

It is off by less than a cent, but it still won't allow me to buy.

**Comment by camelpac** [comment]
Hi,
this is the sdk for using the alpaca api so your issue is not with the sdk.
If the issue persists I would use the slack channel/the community forum to ask account related questions.
closing this issue for now, please do post a message if you have more questions.
