### ISSUE TITLE
422 Client Error: Unprocessable Entity for url

### ISSUE THREAD

**Issue by edukaded** [alpacahq/alpaca-trade-api-python#422]
Was trying the demo, 
```
from alpaca_trade_api.rest import REST
api = REST()

api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-08", limit=10, adjustment='raw').df
```
got that error with this message at the bottom
```
alpaca_trade_api.rest.APIError: limit must be large enough to compute an aggregate bar
```

Turns out the time span isn't long enough, use this instead
```
api.get_bars("AAPL", TimeFrame.Hour, "2021-02-08", "2021-02-12", limit=10, adjustment='raw').df
```
Can someone please fix the readme?

**Comment by Thermoflux** [comment]
I have the same issue, But using 2021-02-12 is also generating the same issue

**Comment by camelpac** [comment]
updated readme here: https://github.com/alpacahq/alpaca-trade-api-python/pull/454
