### ISSUE TITLE
Can't request multiple stocks with get_bars

### ISSUE THREAD

**Issue by cashes11** [alpacahq/alpaca-trade-api-python#423]
The new get_bars method doesn't accept a list of symbols like the old get_barset method. When provided a list of stocks, this error happens: API error: invalid symbol

**Comment by camelpac** [comment]
Hi, the new get_bars supports only 1 symbol at a time. you should use the slack channels/forum webpage to add the feature request. this is a client side sdk, so you can't change apis here.
