### ISSUE TITLE
add 'qty' and 'percentage' arguments to close_position() 

### ISSUE THREAD

**Issue by batmax2015** [alpacahq/alpaca-trade-api-python#434]
The function alpaca_trade_api.rest.close_position() only accepts the 'symbol' argument. Since fractional shares are now available, the 'qty' and 'percentage' options should also be implemented.

I am happy to do it if this enhancement is OK?

**Comment by camelpac** [comment]
This PR adds the functionality: https://github.com/alpacahq/alpaca-trade-api-python/pull/446
