### ISSUE TITLE
401 Client Error: Unauthorized for url: https://api.polygon.io

### ISSUE THREAD

**Issue by SaviourSelf** [alpacahq/alpaca-trade-api-python#44]
I'm going through the tutorial, and I'm getting an exception:

```
DEBUG:urllib3.connectionpool:https://api.polygon.io:443 "GET /v1/historic/agg/day/ATVI?from=2015-8-25&to=2018-12-6&apiKey=abcd HTTP/1.1" 401 None
WARNING:__main__:ATVI generated an exception: 401 Client Error: Unauthorized for url: https://api.polygon.io/v1/historic/agg/day/ATVI?from=2015-8-25&to=2018-12-6&apiKey=abcd

```
Previously I was getting an exception: 
`alpaca_trade_api.rest.APIError: access key verification failed : request is unauthorized (generate APCA-API-KEY-ID and APCA-API-ACCESS-SECRET-KEY from dashboard and include in HTTP header) (Code = 40110000) (Code = 40110000)`
but I regenerated the key, and now the above exception is being returned. 

I creating the REST api client like this: 
`api = tradeapi.REST(key, skey, base_url='https://paper-api.alpaca.markets')`

**Comment by SaviourSelf** [comment]
Comments from Slack:

> The Polygon data API is not available for users who do not have a brokerage account. If you're on a papertrade-only account, you'll need to use Alpaca's data API. Working on clarifying documentation around this now.

**Comment by DreadfulCode** [comment]
> Working on clarifying documentation around this now. 

Any time this year of 2019??

**Comment by alias-noa** [comment]
I have a funded account and used to be able use polygon but no longer can.  Did they change something? I'm getting this error now...
