### ISSUE TITLE
Missing Key 'n' in entity mapping

### ISSUE THREAD

**Issue by haron4igg** [alpacahq/alpaca-trade-api-python#459]
Hi! 

It looks like web api was updated recently, with two extra fields: 'n', 'vw'
`{'t': '2021-06-28T04:00:00Z', 'o': 10.15, 'h': 10.3, 'l': 10.04, 'c': 10.04, 'v': 20356, 'n': 111, 'vw': 10.113978}`
So now conversion to pandas dataframe using '.df' method fails with exception

```
Traceback (most recent call last):
  File "\divscan.py", line 548, in <module>
  File "\divscan.py", line 293, in prepareData
    data = fetchDelta(ticker, TimeFrame.Day, minBars, past, now)
  File "\divscan.py", line 279, in fetchDelta
    df = fetchData(ticker, tf, start, end)
  File "\divscan.py", line 258, in fetchData
    return data.df
  File "\lib\site-packages\alpaca_trade_api\entity_v2.py", line 61, in df
    df.columns = [self.mapping[c] for c in df.columns]
  File "\lib\site-packages\alpaca_trade_api\entity_v2.py", line 61, in <listcomp>
    df.columns = [self.mapping[c] for c in df.columns]
KeyError: 'n'
```

**Comment by nguyenhung** [comment]
I have the same issue and fixing it temporarily by adding the mapping definition in `entity_v2.py` 

```
bar_mapping_v2 = {
    "S": "symbol",
    "o": "open",
    "h": "high",
    "l": "low",
    "c": "close",
    "v": "volume",
    "t": "timestamp",
    "n": "n",
    "vw": "vw",
}


class EntityListType(Enum):
    Trade = Trade, trade_mapping_v2
    Quote = Quote, quote_mapping_v2
    Bar = Bar, bar_mapping_v2
```

The returned dataframe will have `n` and `vw` column

**Comment by Will695** [comment]
yeah i've just edited mine too. Don't know what the n stands for but i would assume vw is VWAP

**Comment by mrmushfiq** [comment]
Having the same issue

**Comment by erickalfaro** [comment]
I dont want to speculate but this API returns exactly what the Polygon API aggregate_bars API returns. 

VW stands for volume weighted average price.

https://polygon.io/docs/get_v2_aggs_ticker__stocksTicker__range__multiplier___timespan___from___to__anchor

**Comment by erickalfaro** [comment]
Simple solution:

```
r = alpaca_api.get_bars('AAPL'
, TimeFrame.Minute
, pd.Timestamp('2021-02-01 00:00:00', tz=timezone('UTC')).isoformat() # start.tz_convert('UTC').isoformat()
, pd.Timestamp('2021-03-01 00:00:00', tz=timezone('UTC')).isoformat() # end.tz_convert('UTC').isoformat()
, limit=4
, adjustment='raw')
df = pd.read_json(json.dumps(r._raw))
```

**Comment by camelpac** [comment]
Hi guys, this commit fixes this issue: https://github.com/alpacahq/alpaca-trade-api-python/commit/b352ea3e853b3b810d43afce01d330c718ab5dd4
and you can use v1.2.3 of the sdk. 
closing this issue.
