### ISSUE TITLE
API authorization error

### ISSUE THREAD

**Issue by physixfan** [alpacahq/alpaca-trade-api-python#470]
I find one of my old piece of code does not work any more. This is the code I use to get authorized:

```
api = tradeapi.REST(Alpaca_API_Key_ID, Alpaca_Secret_Key, base_url='https://paper-api.alpaca.markets')
df1_original = api.polygon.historic_agg_v2(ticker_1, 1, 'day', _from=start_date, to=end_date).df
```

However, now I see the following error:

> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.polygon.io/v2/aggs/ticker/UPRO/range/1/day/2020-01-01/2021-07-20?unadjusted=False&apiKey=(Alpaca_API_Key_ID)

Is it because the breakup between alpaca and polygon (I did not follow the exact news closely). If so, what should we do?

**Comment by camelpac** [comment]
Hi, yes. Polygon data is not supported anymore. 
You need to use the Alpaca Data V2 endpoint. 
Read the readme of this project to learn more about it.

**Comment by physixfan** [comment]
> Hi, yes. Polygon data is not supported anymore.
> You need to use the Alpaca Data V2 endpoint.
> Read the readme of this project to learn more about it.

Thanks for the clarification! What's the correct way to get the daily data now? I have read the readme but I don't think the information is very detailed 😂

I see this line in the readme for getting historical data but it is not daily data:

`api.get_quotes("AAPL", "2021-02-08", "2021-02-08", limit=10).df`

**Comment by srgustafson8** [comment]
@physixfan I think you're looking for [bars](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/historical/#bars)

**Comment by physixfan** [comment]
Thanks! It works!
