### ISSUE TITLE
Please improve method to access classes/dictionary values

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [alpacahq/alpaca-trade-api-python#472]
Hi. Currently, the classes implemented are only accessible through '.', and dictionaries are only accessible through '[key]'. The problem is the program can return objects as either wrapped in classes or raw dictionaries. Please implement a method in classes, so we can use a unified method to access values by keys.

**Comment by camelpac** [comment]
Hi could you give an example?

**Comment by 2young-2simple-sometimes-naive** [comment]
> Hi could you give an example?

If I use `api.list_orders()` to get my orders, it returns a class object. While the orders I got from`alpaca.stream.Stream(base_url=APCA_API_BASE_URL, key_id=APCA_API_KEY_ID, secret_key=APCA_API_SECRET_KEY, data_feed="iex", raw_data=True)` are python dictionaries. It is really complicated to deal with orders like the following:

> 
> try:
>     order_type = order.order_type
> except:
>     order_type = order['order_type']

because I have to write this for all components of the order.

I wish I can use `order_type = order['order_type']` to deal with orders regardless of the data type, if you can update the class order, and allow me to call order components with brackets.

**Comment by camelpac** [comment]
Hi, each data returned from the api has "object" and "raw" forms.
when you pass `raw_data=True` you will get dictionary. if you use `False` you will get an object.

on your order object, if you use `order._raw` you will get a dictionary. so you can select what type of data to work with.

**Comment by drew887** [comment]
Hey closing this one out due to inactivity
