### ISSUE TITLE
_data_get_v2() throws "NoneType object is not iterable" exception when no bars data is available

### ISSUE THREAD

**Issue by kartiksubbarao** [alpacahq/alpaca-trade-api-python#478]
Example code to reproduce error:

```api.get_bars('GLTA', alpaca_trade_api.rest.TimeFrame.Day, '2016-08-17', '2021-08-16')```

This happens because the `bars` key in the `resp` dict is `None` (as opposed to undefined) on line 563 of rest.py, so `items` doesn't get properly assigned the empty array as intended. A simple fix is to change line 563 to this:

```items = resp.get(endpoint, []) or []```

**Comment by LordyHun** [comment]
Bump. Just found this issue today.

**Comment by gnvk** [comment]
Fixed by https://github.com/alpacahq/alpaca-trade-api-python/commit/0d5f4343eb8483c6b56b26e4f408a9c08d70226b
