### ISSUE TITLE
get_barset is deprecated

### ISSUE THREAD

**Issue by maxencefaldor** [alpacahq/alpaca-trade-api-python#482]
Hi,

In the README, I see that `get_barset` is deprecated [here](https://github.com/alpacahq/alpaca-trade-api-python#using-get_barset-deprecated-use-get_bars-instead), and that we should use `get_bars` instead.

But `get_barset` achieves a different function. We cannot retrieve bars for different symbols with `get_bars`.
Is there a non-deprecated method to retrieve bars for different symbols like `get_barset`?

Thanks!

**Comment by gnvk** [comment]
`get_bars` now supports different symbols. And for better performance (on many symbols), you can also use `rest_async.get_bars_async`.
