### ISSUE TITLE
api.get_barset time frame.

### ISSUE THREAD

**Issue by tlh45342** [alpacahq/alpaca-trade-api-python#487]
if testing....

import pandas
import alpaca_trade_api as tradeapi
import os
API_KEY = os.environ.get('API_KEY')
API_SECRET = os.environ.get('API_SECRET')
api = tradeapi.REST(API_KEY, API_SECRET, base_url='https://paper-api.alpaca.markets')
api.get_bars("APPL", "minute", start='2021-09-09', end='2021-09-10', limit=1000, adjustment='raw').df

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python39\lib\site-packages\alpaca_trade_api\rest.py", line 651, in get_bars
    bars = list(self.get_bars_iter(symbol,
  File "C:\Program Files\Python39\lib\site-packages\alpaca_trade_api\rest.py", line 634, in get_bars_iter
    timeframe=timeframe.value,

Please note: master/alpaca_trade_api/rest.py line 634 reads as "timeframe=timeframe.value," 

I am guessing  "timeframe" should not have **.value** added to it?

**Comment by gnvk** [comment]
"minute" is not a correct timeframe. However, this should be fixed now for valid timeframes, e.g. "1Min", "5Min", "2Hour", "5Day". Please check the latest version and if it's working close the issue.

**Comment by tlh45342** [comment]
I will close this out in any event and look at this later.  Thanks.
