### ISSUE TITLE
says qty is required when submitting an order with a notional value

### ISSUE THREAD

**Issue by JESIII** [alpacahq/alpaca-trade-api-python#490]
```
order = api.submit_order(symbol=stock.upper(), notional=5000, side='buy', type='market', time_in_force='day')
  File "C:\ProgramData\Anaconda3\lib\site-packages\alpaca_trade_api\rest.py", line 347, in submit_order
    resp = self.post('/orders', params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\alpaca_trade_api\rest.py", line 179, in post
    return self._request('POST', path, data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\alpaca_trade_api\rest.py", line 139, in _request
    return self._one_request(method, url, opts, retry)
  File "C:\ProgramData\Anaconda3\lib\site-packages\alpaca_trade_api\rest.py", line 168, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: qty is required
```

says qty is required when submitting an order with a notional value and then when I try to submit an order with both it says I shouldn't have qty, which is true, but why isn't notional working by itself?

**Comment by tifolson** [comment]
I'm having a similar issue. 

When I use notional:
alpaca.submit_order(symbol='SPY', notional=600,  side='buy', type='market', time_in_force='day')
**alpaca_trade_api.rest.APIError: qty is required**

When I use qty with a fractional amount:
alpaca.submit_order(symbol='SPY', qty=1.5, side='buy', type='market', time_in_force='day')
**alpaca_trade_api.rest.APIError: qty must be integer**

**Comment by jacob-hutchings** [comment]
I am also having the "qty is required" problem when using notional.

Can anyone from Alpaca chime in?

**Comment by tifolson** [comment]
I'm not from Alpaca, but I was able to resolve this by resetting my paper account. I did this after another user on Alpaca's Community Forum reset his account and cited this article: https://alpaca.markets/docs/trading-on-alpaca/fractional-trading/

**Comment by jacob-hutchings** [comment]
@tifolson That worked. Thank you!

**Comment by EmersonDove** [comment]
> I'm not from Alpaca, but I was able to resolve this by resetting my paper account. I did this after another user on Alpaca's Community Forum reset his account and cited this article: https://alpaca.markets/docs/trading-on-alpaca/fractional-trading/

Worked for me to

**Comment by tifolson** [comment]
@jacob-hutchings @EmersonDove yay! You're welcome!

**Comment by sixcorners** [comment]
Just an fyi to anyone who finds this later: https://forum.alpaca.markets/t/is-it-a-bug-in-alpaca/7369/5  
If the paper account is older than 2021 it doesn't support notional.
