### ISSUE TITLE
Feature Request: Customizable TimeFrame

### ISSUE THREAD

**Issue by AlphaGit** [alpacahq/alpaca-trade-api-python#492]
We'd like to be able to use variable versions of the TimeFrame, to accommodate different scenarios that we require for barsets.

An ideal usage of the API would be something like this:

```python
rest_api = REST()
time_frame = TimeFrame(15, TimeFrameUnit.minutes)
result = api.get_bars("APPL", time_frame, start='2021-09-09', end='2021-09-10', limit=1000, adjustment='raw').df
```

Relates to #487 and #417

**Comment by AlphaGit** [comment]
I have started a draft approach to this and will be submitting a PR very soon, but wanted to give the chance of discussing approaches before wrapping up the working proposal.

**Comment by drixie** [comment]
This is not working. Importing TimeFrameUnit throws an error. See #522
