### ISSUE TITLE
Portfolio history params are ignored (broker API)

### ISSUE THREAD

**Issue by sommohapatra** [alpacahq/alpaca-trade-api-python#497]
Sending a GET to portfolio history API, "/v1/trading/accounts/{account_id}/account/portfolio/history" with params {  "timeframe": "15Min"}, for example, sends me back data with "1D" timeframe. In fact, none of the params have worked for me. I figured it was an issue with how I was sending parameters, but other v1 APIs are working.

**Comment by haxdds** [comment]
Please post this issue on the Alpaca-API repo. Issues related to the trade API should be posted to this repo.
