### ISSUE TITLE
[Feature] : Add GitHub Issue Forms

### ISSUE THREAD

**Issue by Hard-Coder05** [alpacahq/alpaca-trade-api-python#508]
## Summary

As we can see the repository has no predefined Issue template, because of which there is non uniformity in the issues section.

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

**Comment by Hard-Coder05** [comment]
If you find this a valuable addition to the project, then do assign me! I would love to contribute :)

**Comment by haxdds** [comment]
Resolved with PR #513
