### ISSUE TITLE
 certificate verify failed: certificate has expired

### ISSUE THREAD

**Issue by Oke-Harridon** [alpacahq/alpaca-trade-api-python#510]
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

error during websocket communication: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

**Comment by jbgrunewald** [comment]
What are you doing to get this error? Can you provide a code sample?

**Comment by jbgrunewald** [comment]
Ok, I'm not sure I understand where this is interacting with the client or the API. If it's resolved can we close this issue?

**Comment by hlchan-sg** [comment]
> importing a new SSL certificate on my windows laptop.

Hi Can I check how did you solve this? It will be really nice if you can help laying the detail steps. I am stuck on this for the past month and not been able to solve it. Many thanks.

**Comment by Oke-Harridon** [comment]
Hi, @hlchan-sg I downloaded the certificate, the output message should tell you the name of the certificate that expired and I used certmgr on windows to import the new certificate I downloaded. Just right-click on any item from the list on certmgr on windows you will see the All Tasks option. It's the manage user certificates (certmgr) application on windows not sure about mac but they should have a similar application.

**Comment by hlchan-sg** [comment]
Hi @Oke-Harridon thanks alot for the super fast reply. it helps, just that i do not know what are the certs that i am running problem with. I have finally managed to solve it today! Thanks a lot.

For future people who has problem finding what is the problem cert, you can refer to this post https://stackoverflow.com/questions/64298017/python-certificate-verify-failed-unable-to-get-local-issuer-certificate

below are the steps i taken:
1. go to https://www.digicert.com/help/
2. key this in the server address: https://paper-api.alpaca.markets'
3. look at the immediate subject cert, these are the certs required to make things work
4. then go google and find it to download
5. in windows type run certmgr
6. under trusted root certification, right click import the downloaded file
