### ISSUE TITLE
TradingStream should respect the raw_data=True parameter from Stream

### ISSUE THREAD

**Issue by asxzy** [alpacahq/alpaca-trade-api-python#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The Stream class has a parameter `raw_data` which controls the returned data to be an Alpaca Entity or Dict. 
When init Stream instance, the object will init a TradingStream instance and DataStream instance. The `raw_data` parameter was passed to DataStream but not passed to TradingStream (Not implemented in TradingStream either). Thus TreadingStream will dispatch the data as an Alpaca Entity disregarding `raw_data` parameter. 

As a user, this behavior is unexpected, when passing `raw_data=True` to Stream, I would expect all callbacks receives the raw data as my input. However, on `update_trades` event, the input is an Entity instead of a Dict.

For now, I can access the raw data within trading_updates callbacks by `var._raw`. but it would be great if the TradingStream respect the raw_data parameter out-of-the-box.

### Describe the solution you'd like.

In TradingStream, inherit `raw_data` parameter from Stream and implement dispatch raw_data.

**Comment by gnvk** [comment]
This should be fixed in v1.5.0. @asxzy can you please close the issue if that's the case?

**Comment by asxzy** [comment]
> 

Thank you for the update. closing
