### ISSUE TITLE
[Bug]: data not adjusted for splits

### ISSUE THREAD

**Issue by emil-k** [alpacahq/alpaca-trade-api-python#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

RMBL had a 1/20 split on 2020-05-20. When I request the daily bars including this timeframe, with `adjustment="split"` option, the data comes back unadjusted.
![image](https://user-images.githubusercontent.com/8834497/147450602-d38eee16-9069-47af-b904-69fc50d60973.png)

### Expected Behavior

Data should come back adjusted for splits.

### Steps To Reproduce

```markdown
api.get_bars(
                ["RMBL"],
                TimeFrame(1, TimeFrameUnit.Day),
                "2020-05-19",
                "2020-05-20",
                adjustment="split",
            ).df
```

**Comment by haxdds** [comment]
Hi emil-k, thanks for posting an issue. I could not not reproduce the issue you described.

This is the code I ran with alpaca-trade-api version 1.4.3.

What version of python and alpaca trade api are you using?

```
bars = rest_api.get_bars(['RMBL'], 
                             TimeFrame(1, TimeFrameUnit.Day), 
                             '2020-05-19', 
                             '2020-05-20', 
                             adjustment='split').df
bars
```


**open | high        | low      | close      | volume       | trade_count    | vwap                | symbol**
9.74      | 10.380   | 9.2       |  9.66      | 532915      | 13452              | 9.838260         | RMBL
9.16      | 14.821    | 8.0       | 9.25       | 2163597    | 23209             | 10.208243       | RMBL

**Comment by emil-k** [comment]
Hello @haxdds , I have also raised this issue on slack ([link here](https://alpaca-community.slack.com/archives/CEL9HCSN4/p1641044577338800)), and it was fixed by your team. There, however, many more similar issues. If you look at the slack thread you can see more screenshots and a pickle file I attached, that should be a good starting point.
