### ISSUE TITLE
get_bars() for regular trading hours only (no extended/after hours data)

### ISSUE THREAD

**Issue by kitt-th** [alpacahq/alpaca-trade-api-python#552]
Hello,

I've scoured here and the alpaca forums for answers to this question but have not yet found any info.

I'd like candle/bar data for regular trading hours only, but continue to received extended hours candle data.
I've seen no parameter for this in get_bars() documentation or code, nothing in the environment variables etc.

Up against a brick wall here - can anyone assist me with this? Am I missing something super simple?

Regards & thanks in advance.

**Comment by gnvk** [comment]
There is no server-side option for this. But it's really easy to filter out non trading hour bars on the client side. See https://github.com/alpacahq/alpaca-trade-api-python/issues/457#issuecomment-1002842230 for an example.

**Comment by kitt-th** [comment]
thanks :)
