### ISSUE TITLE
get email address from API keys

### ISSUE THREAD

**Issue by hz2018tv** [alpacahq/alpaca-trade-api-python#554]
which api to get account email address from API keys? been using APIs for a while and want to login web interface.

**Comment by haxdds** [comment]
hi hz2018tv, there isn't an API endpoint to retrieve account login details. I am curious as to what your desired use case is for this feature. Why do you wish to retrieve your email address via API?

**Comment by hz2018tv** [comment]
I have been using the API keys for a while, then I found I fogot which email address I used to register that account when I tried to login the web interace.
