### ISSUE TITLE
Polygon API hits 500 upon handle_data call

### ISSUE THREAD

**Issue by LiamBui** [alpacahq/alpaca-trade-api-python#56]
Hey there,

I've recreated this ticket from the pylivetrader repository, because this is primarily an issue on the side of Polygon, I believe. 

Link to the issue at hand: https://github.com/alpacahq/pylivetrader/issues/82

**Comment by Rybaco** [comment]
I've been getting the same with historical_agg calls from this repository, each call gets a http 500 server error the first time, works for about an hour, and then it resets and the error starts popping up again

**Comment by ajaceves** [comment]
Having the same issue with historical_agg calls. The link returned as part of the raised HTTPError works if pasted manually into a browser.

**Comment by ttt733** [comment]
Closing this because it was probably fixed when Polygon's API went to v2.
