### ISSUE TITLE
Close_all_positions and cancel_all_orders don't work properly 

### ISSUE THREAD

**Issue by elieobeid7** [alpacahq/alpaca-trade-api-python#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`api.close_all_positions` and `api.cancel_all_orders` don't work properly, especially if you have more than 1 quantity for a share. Try to buy 4 shares of Facebook and try to close them, and then run

`api.list_orders(status='open')`

you see it still there in the response.

also:

`def close_position(symbol, qty)`

notice it takes symbol and quantity, but if you try to give quantity, you get this error

`TypeError: close_position() takes 2 positional arguments but 3 were given`

**Comment by camelpac** [comment]
Hi, regarding the close_position.
the `qty` argument must be named. 
so this won't work:
```
close_position("AAPL", 10)
```

but this will work:

```
close_position("AAPL", qty=10)
```

**Comment by elieobeid7** [comment]
I'd say this is a code inconsistency, one argument shouldn't be named but the other yes, and every API call is different

**Comment by drew887** [comment]
Hey @elieobeid7 sorry about the delay and confusion on this one. 

Since its solved am I good to close it out? 

At this point changing the structure of this call to not have it be a positional argument would likely be a breaking change so I don't want to make it at this time.

**Comment by rm-rf-etc** [comment]
Why would `close_position` take a quantity parameter? The name already says quite clearly, **close** the position, meaning, **_all of it_**. This is not the same as _sell_, which looks like we have `submit_order` for that.
