### ISSUE TITLE
api.get_position throws an exception for certain symbols

### ISSUE THREAD

**Issue by elieobeid7** [alpacahq/alpaca-trade-api-python#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Run 

`print(api.get_position('AAPL'))`

you get this error

```
rest.py", line 217, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: position does not exist
```

**Comment by camelpac** [comment]
Hi, 
not sure what the cause of this error but just a thought - are you using the paper account or the real account?
make sure you init the `api` object accordingly.

**Comment by elieobeid7** [comment]
I'm using the paper account. And the API is initialized correctly, other calls in the class are working.

**Comment by drew887** [comment]
Hey sorry about the delay on this one @elieobeid7 I believe this error is raised from the API itself when you ask for a position in your account that you don't have, even if the symbol is real. 

Is this error still happening for symbols in which your account does have positions in? :thinking:
