### ISSUE TITLE
[Bug]: `as` python-native keyword used as member variable name in QuoteV2

### ISSUE THREAD

**Issue by matt7045** [alpacahq/alpaca-trade-api-python#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to access the 'ask size' in a QuoteV2 object, a syntax error arises. The name of the member variable is `as`. `as` is a python keyword, and as a result the aforementioned syntax error arises. 

### Expected Behavior

When accessing the `ask size` variable in a QuoteV2 object, a syntax error should not occur, and the ask size should be returned. 

### Steps To Reproduce

```markdown
1. Start IDLE
2. Create a QuoteV2 object
3. Attempt to access the `.as` field of that object
4. Experience syntax errors
```

### Anything else?

Here is a screenshot of the current behavior.
![image](https://user-images.githubusercontent.com/6487008/152927133-0d29e800-af65-474a-b5db-057ab86e6aa4.png)

**Comment by gnvk** [comment]
You can use `y.ask_size` to get the ask size of the quote.
