### ISSUE TITLE
[Bug]: Assets with status "active" return empty dataframe in get_bars

### ISSUE THREAD

**Issue by AlejandroRigau** [alpacahq/alpaca-trade-api-python#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do `api.list_assets(status='active') `I get a list of assets that I would expect have some data but when I do `api.get_bars("FNEVY", TimeFrame(1, TimeFrameUnit.Minute), "2022-02-15", "2022-02-16", adjustment='raw').df`
it seems to return an empty dataframe.

### Expected Behavior

I would expect it to return something because it was in the list of active assets.

**Comment by OlegRa** [comment]
A brief check on Yahoo finance shows that this asset is not very active - the last non-empty bar is for Dec 30, 2021, and no trading activity since that time. The `active` status on Alpaca means that you can trade this asset but doesn't guarantee that anyone else did/do the same.
