### ISSUE TITLE
Request ability to cancel order by client order id

### ISSUE THREAD

**Issue by ztaylor54** [alpacahq/alpaca-trade-api-python#59]
If we are able to tag our orders with a Client Order ID, it seems reasonable for a call like `api.cancel_order_by_client_order_id('my_custom_client_order_id')` to exist. I ask because it seems rather confusing to provide developers with a nice way of tagging orders internally, then forcing them to query for the proper id with a call to `get_order_by_client_order_id` if they chose to use that feature.

**Comment by ttt733** [comment]
I've opened an issue for this on our Alpaca-API tracker, as I mentioned on the PR. When this feature is added to the backend, the SDK will be updated with support for it.
