### ISSUE TITLE
Add asset type to asset object

### ISSUE THREAD

**Issue by hashvest** [alpacahq/alpaca-trade-api-python#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, the list assets and the get asset endpoints/method return object(s) that don't contain the asset type. I need to know the type of asset I am working it so I can filter away assets like penny stocks and ETF's.

### Describe the solution you'd like.

We need to know if the asset is a common stock, penny stock, ETF e.t.c I checked polygon's documentation and I observed that the asset type is attached to the asset object.

Thanks

**Comment by drew887** [comment]
Hey @hashvest this kind of an issue is a bit outside of the scope of this repo as that would require changes to the API itself. 

Please open an issue over [here in this repo](https://github.com/alpacahq/Alpaca-API) which is dedicated directly to gathering feedback on the API itself :slightly_smiling_face:
