### ISSUE TITLE
[Bug]: 'REST' object has no attribute 'get_last_trade'

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-trade-api-python#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You get this error:
'REST' object has no attribute 'get_last_trade'

### Expected Behavior

No error

### Steps To Reproduce

```markdown
use this environment:

Python 3.10
alpaca_trade_api==2.0.0
pandas==1.4.1
numpy==1.22.3
```

### Anything else?

No

**Comment by drew887** [comment]
Hey @sshcli the `get_last_trade` and `get_last_quote` functions were deprecated a while back with the other market-data v1 functionality and were replaced with `get_latest_trade` and `get_latest_quote`.

**Comment by sshcli** [comment]
Thanks @drew887
