### ISSUE TITLE
[Bug]:  ModuleNotFoundError: No module named 'alpaca_trade_api.stream'

### ISSUE THREAD

**Issue by EM5813** [alpacahq/alpaca-trade-api-python#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to stream data but I keep getting the error

ModuleNotFoundError: No module named 'alpaca_trade_api.stream'

I’ve tried pip3 install alpaca_trade_api  from here: https://stackoverflow.com/questions/62745845/modulenotfounderror-no-module-named-alpaca-trade-api

Currently Anaconda is using version

alpaca-backtrader-api 0.13.1 

Any suggestions?

### Expected Behavior

python3 main.py should work

**Comment by drew887** [comment]
Hey @EM5813, you mentioned there you're using alpaca-backtrader-api 0.13.1, does it work if you upgrade that to 0.15.0 ?

**Comment by EM5813** [comment]
Thanks for quick response. I tried to uninstall then install but now it doesn't show under pip3 list. 

Steps taken:

1. pip3 uninstall alpaca-trade-api
2. pip3 install alpaca-trade-api
3. pip3 list
    not there

Image attached. 
<img width="401" alt="Screen Shot 2022-04-13 at 1 10 29 PM" src="https://user-images.githubusercontent.com/24214863/163262202-8dc09e29-3644-4db6-97d1-19e37c20ef97.png">

Incidentally, I get the same error ModuleNotFoundError: No module named 'alpaca_trade_api.stream' when using python and pipenv. With  alpaca-trade-api  "version": "==2.0.0

**Comment by EM5813** [comment]
Fixed. I  had to delete another alpaca-trade-api version on my system.  Thanks for the help.
