### ISSUE TITLE
[Question]: list_orders() Quantity

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-trade-api-python#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is not a bug, it is a question.
I can't find any documentation or example about this.

I know how to show a list of orders:
```
api = alpaca.REST(api_key, api_secret, base_url, api_version='v2')  
ORDERS = api.list_orders()
```

But what I don't know, is how to get the quantity of orders I have open right now.
I don't have the order id, I just have the symbol

**For example:** 
I want to know the exact qty of open orders I have to sell TSLA to avoid submitting another order.

Thanks in advance for your response.

### Expected Behavior

Get orders qty 

### SDK Version I encountered this issue in

Alpaca-trade-api- == 2.0.0

### Steps To Reproduce

```markdown
Try to get the quantity of open orders for a given symbol (Ex: TSLA)
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by drew887** [comment]
Hey @sshcli sorry about the issues with the bug template there, we're going to add a template for generalized questions. 

If you want to get the list of open orders for a specific set of symbols `list_orders` takes a `symbols` parameter that lets you filter to a list of specific symbols. 

For example:
```python
api = alpaca.REST(api_key, api_secret, base_url, api_version='v2')  
ORDERS = api.list_orders(symbols=['TSLA'])
```
Is that what you were looking for ?

**Comment by sshcli** [comment]
> Hey @sshcli sorry about the issues with the bug template there, we're going to add a template for generalized questions.

Great, no problem.

> Is that what you were looking for ?

No. What I want to get is the quantity of all open orders. the result must be a integer number. For example: 3

**Comment by drew887** [comment]
Ah sorry, did you mean the sum of the quantity field of all open orders? Not just the number of orders?

If that's the case then that's not really something we need to provide direct capabilities too into the SDK imo, as it would be common/easy enough to do it with general python functionality. IE reducing over the list of returned orders or using a for loop would be the first things that come to mind.

For example does something like :
```python
from functools import reduce

api = alpaca.REST(api_key, api_secret, base_url, api_version='v2')  
orders = api.list_orders(symbols=['TSLA'])

total_qty = reduce(
      lambda result, order: result + int(order.qty),
      orders,
      0
)
```
give you the result you're looking for?

**Comment by sshcli** [comment]
> Ah sorry, did you mean the sum of the quantity field of all open orders? Not just the number of orders?

Yes. Exactly

> give you the result you're looking for?

Yes man, you are the best!
Thank you very much. 
I owe you one

**Comment by sshcli** [comment]
Just to let you know, the above code will give the qty of stocks in the order, 
it does not give you the sum of all orders

**Comment by sshcli** [comment]
> Not just the number of orders?

Just the number of orders

**Comment by sshcli** [comment]
```
from functools import reduce

api = alpaca.REST(api_key, api_secret, base_url, api_version='v2')  
orders = api.list_orders(symbols=['TSLA'])

total_qty = reduce(
      lambda result, order: result + int(order.qty),
      orders,
      0
)
```

The above code is almost the same as api.get_position(SYMBOL).qty, but for the orders.

it is not what I need.
I need the sum of all orders, no matter what symbol.
I looks like something very easy, but truth is i don't know how to get it and I can't find any documentation about this.

**Comment by drew887** [comment]
Sorry this is getting a little confusing as it seems like you're contradicting yourself between responses here. 

Are you now saying you just need the number of open orders for your account? 
If thats true then does going back to your original example of:
```python
api = alpaca.REST(api_key, api_secret, base_url, api_version='v2')  
ORDERS = api.list_orders()
```
Does `len(ORDERS)` not just give you the total number of open orders in your account?

What specifically do you mean by `sum of all orders` ?

**Comment by sshcli** [comment]
@drew887 Sorry man, my mistake
`len(ORDERS)` is the man.

Thanks again and sorry for the inconvenience
