### ISSUE TITLE
[Feature Request] api.list_orders(side='Buy or Sell')`

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-trade-api-python#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

> Is your feature request related to a problem? 

Yes, we need an easy way to get the list of orders by side (Buy or Sell)

### Describe the solution you'd like.

According to documentation here:
https://alpaca.markets/docs/api-references/trading-api/orders/

To Get a list of orders: `list_orders()`

The only available query parameters attributes are:
```
status
limit
after
until
direction
nested
symbols
```

My suggestion is that we also need this one:
`side`

For example:
`api.list_orders(side='sell')`

### Describe an alternate solution.

As a workaround you could try to get this information by adding extra Python code to your program.
But IMHO, simple is better than complex

**Comment by drew887** [comment]
Hey @sshcli sorry about this one as it seems to be a bit of a case of running mis-documentation across several places :disappointed: . 

All that aside it seems like this actually might be possible in the current sdk its just not got a nice way to go about getting it at the moment.

list_orders takes an optional `params` param where you can add additional query params if you need (like in a case like this where the sdk is out of sync with the api).

does the following: 
```python
api.list_orders(params={'side':'sell'})
```
work for you?

Either way list_orders does need updated to have this but hopefully passing it via `params` works for you in the meantime :disappointed:

**Comment by sshcli** [comment]
> sorry about this one as it seems to be a bit of a case of running mis-documentation across several places 😞 

Yeah, you are right. 
In my case, I always try to find answer to my questions in the Knowledgebase, FAQs, Google, etc.
I don't like to bother anyone, trust me.
But if I can't find the answer to my question, I always end asking on Stackoverflow, Github, etc.



> work for you?

Yes man, it works. Thanks



> Either way list_orders does need updated to have this

it's feel great when a feature request is taken into consideration

**Comment by sshcli** [comment]
@drew887  `api.list_orders(side='sell')` is it's working as expected in 2.1.0
Great Job. Thanks
