### ISSUE TITLE
[Feature Request] api.cancel_all_orders(side='buy')

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-trade-api-python#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

According to de documentation here:
https://alpaca.markets/docs/api-references/trading-api/orders/

You can only cancel all orders, there is no parameters to specify the side you want to cancel. (Buy or Sell)

The following optional params does not work here:
`api.cancel_all_orders(params={'side':'buy'})`
`api.cancel_all_orders(params={'side':'sell'})`

### Describe the solution you'd like.

We need an easy way to cancel all orders filtered by the side (Cancel all buy orders or cancel or sell orders)

We need something like these:
`api.cancel_all_orders(side='buy')`
`api.cancel_all_orders(side='sell')`

### Describe an alternate solution.

As a workaround you could try to perform this task by adding extra Python code to your program.
But IMHO, simple is better than complex

### Anything else? (Additional Context)

Hopefully, we can have this feature in alpaca-trade-api 2.0.1 along with the PR https://github.com/alpacahq/alpaca-trade-api-python/pull/610

**Comment by drew887** [comment]
Hey @sshcli in this instance this isn't something we can fix with the SDK as I don't believe the API endpoint itself doesn't supports this functionality :disappointed:. 

Please open an issue over [here](https://github.com/alpacahq/Alpaca-API) if you'd like to see it added to the API.

In the meantime the best suggestion I can offer is fetching the list of all orders for the type you need and looping over the list making separate calls to `cancel_order` with timeouts to ensure you don't hit api limits. :sweat:

**Comment by sshcli** [comment]
> Please open an issue over [here](https://github.com/alpacahq/Alpaca-API) if you'd like to see it added to the API.

Done.
See here: https://github.com/alpacahq/Alpaca-API/issues/229

Once again, thanks for your kind response.

Regards,
