### ISSUE TITLE
[Question]: Is there a way to subscribe to an account updates stream?

### ISSUE THREAD

**Issue by ckinateder** [alpacahq/alpaca-trade-api-python#613]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

The only way I could find to get the current portfolio valuation is to poll the rest api. Is there a stream for this? For like "account updates"?

**Comment by drew887** [comment]
Ah sorry at this time there is only the trade_updates, and market data streams available in the api itself :disappointed:.

If you'd like to see a stream added for account activities I'd encourage you to please go [here](https://github.com/alpacahq/Alpaca-API) and open an issue stating you'd like to see a stream added to the API.
