### ISSUE TITLE
get_crypto_bars method not returning correct number of bars

### ISSUE THREAD

**Issue by sigmoid1077** [alpacahq/alpaca-trade-api-python#616]
return self.api.get_crypto_bars(
    symbol=self.symbol,
    timeframe=alpaca_trade_api.TimeFrame.Minute,
    start=(datetime.datetime.now(tz=datetime.timezone.utc) - datetime.timedelta(minutes=60)).isoformat(),
)

The length is 141, but should be 60.

**Comment by drew887** [comment]
Also in the future please use the issue templates we have
