### ISSUE TITLE
[Question]: get 50MA with Alpaca

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-trade-api-python#619]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

With yahoo, I can get 50MA with this:
`yahoo_fin.stock_info.get_data('TSLA', interval='1d')['close'][-50:].mean()`

What is the Alpaca version of the above code?

Thanks in advance for your kind response.

Regards,

**Comment by sshcli** [comment]
I know I can get the bars with this:
`api.get_bars('TSLA', '15Min', limit=200)`

I also know there are some external libraries that can help me to do this job.

But my question is if there is a native way to perform this simple task without implementing additional 3rd party libraries?

**Comment by sshcli** [comment]
So far, this was the easiest workaround that came to my mind:
```
BARS = api.get_bars('TSLA', '1Min')
BARS.reverse()
CLOSE_PRICES = (BARS[0].c, BARS[1].c, BARS[2].c, BARS[3].c, BARS[4].c, BARS[5].c, BARS[6].c, BARS[7].c, BARS[8].c)
SMA = round(sum(CLOSE_PRICES) / 9, 2)
```

**Comment by drew887** [comment]
Hey @sshcli sorry for the late response on this one. 

This kind of stuff is why we provide Python Dataframes on results via the `.df` property. 

Every one of your examples uses a different time frame so I'm not sure for what range you're actually trying to get an average over; but here's an example that closely matches your first example of last 50 days. 

Also note that getting the last N days of data isn't really directly supported via the bars api so we have to do a little ground work to figure out when the 50th trading day ago was.  
```python
    current_date = datetime.now(tz=timezone.utc)
    cal = rest.get_calendar(end=current_date.isoformat())

    bars = rest.get_bars(
        symbol='AAPL',
        timeframe=TimeFrame.Day,
        start=cal[-50].date.date(),
        end=cal[-1].date.date(), # in this case we could've also used current_date but still referencing cal for the end date shows how to use a range
    )

    mean = bars.df['close'].mean()
```
Aside from the calendar parts you can see it maps almost exactly to be the same as the yahoo example.

Does this solve your question?

**Comment by sshcli** [comment]
> Hey @sshcli sorry for the late response on this one.

Don't worry. not a problem at all.

> Every one of your examples uses a different time frame so I'm not sure for what range you're actually trying to get an average over

Those are only examples, the time range itself does not matter

> Does this solve your question?

Yes. Thank you for your kind response.

I'm closing this issue as solved.
