### ISSUE TITLE
[Bug]: api.list_orders(side='buy', params={'symbols':SYMBOL})

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-trade-api-python#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`ORDERS_BY_SIDE = api.list_orders(side='buy')` ✔️

`ORDERS_BY_SYMBOL = api.list_orders(params={'symbols':SYMBOL})` ✔️

You can't filter your orders by side + symbol (See the example below)

`ORDERS_BY_BOTH = api.list_orders(side='buy', params={'symbols':SYMBOL})` ❌

### Expected Behavior

This should work:
`ORDERS_BY_BOTH = api.list_orders(side='buy', params={'symbols':SYMBOL})`

You should be able to filter your orders by side + symbol

### SDK Version I encountered this issue in

alpaca-trade-api 2.1.0

### Steps To Reproduce

```markdown
Try to filter filter your orders by side + symbol
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by sshcli** [comment]
Ok, I found the bug why this code is not working:
❌ `ORDERS_BY_BOTH = api.list_orders(side="sell", params={'symbols':"AMD"})` 

It does not work if the sell order is for shorting the stock.
it only works when you have a position and you are trying to sell it.

**Comment by haxdds** [comment]
Hey @sschli, which version of the SDK are you using?

Have you tried directly passing in the symbols as parameters?

https://github.com/alpacahq/alpaca-trade-api-python/blob/6c45474641cf5ac08c876d284eda7bdf6d9e3cde/alpaca_trade_api/rest.py#L316

**Comment by sshcli** [comment]
> Hey @sschli, which version of the SDK are you using?

Thank you for your response.
I'm now using 2.2.0 and following code is working ok:
✔️ `api.list_orders(side="sell", params={'symbols' : 'AAPL'}, limit=20)`

I'm closing this as solved.
Thanks

**Comment by sshcli** [comment]
We have this problem in `alpaca-py 0.7.2`
