### ISSUE TITLE
Question: Can someone explain how the sector weighting in the BenGraham.py file works?

### ISSUE THREAD

**Issue by FrickProgrammer** [alpacahq/alpaca-trade-api-python#63]
I was wondering how the sector weighting in the BenGraham file works. My program lists the sectors by name, and displays an int usually growing from 1.0 to 6.0 next to them. It then assigns stocks a super small decimal for sector weighting say .01011 which I think the code then implies is divided by the sector weight, say 2.0, to give our stock weight. Why is the sector weight not a % of 100.
[output.xlsx](https://github.com/alpacahq/alpaca-trade-api-python/files/3050443/output.xlsx)

**Comment by ttt733** [comment]
Hello, this question would be better discussed in the pylivetrader repository, but you may also find [this](https://medium.com/automation-generation/teaching-your-computer-to-invest-with-python-commission-free-automated-investing-5ade10961e08) article helpful. Please open an issue in the pylivetrader repo if you still have questions after checking that article out.
