### ISSUE TITLE
How to parse api.submit_order() response

### ISSUE THREAD

**Issue by Jacyle** [alpacahq/alpaca-trade-api-python#65]
The response after submitting api.submit_order() returns a data type 'entity.Order'.

I can't figure out how to parse this object to extract information, such as, 'client_order_id'.

api.list_orders() has a similar issue in that it puts these objects into a list.

Is there some other method I should be using to obtain order information? Or perhaps you could provide a snippet of code for helping to parse the 'entity.Order' types.

Thanks

**Comment by tburkholder23** [comment]
There are probably better ways out there, but this is the function that I wrote to handle. Super() objects are super annoying.

get_filled_orders(status, start_date):
    fetch_orders = api.list_orders(status=status, after=start_date)
    orders = []
    for i in range(fetch_orders.__len__()):
        order = fetch_orders[i]._raw
        orders.append(order)
    return pd.DataFrame(orders)

**Comment by ttt733** [comment]
Information can be retrieved from API objects by simply doing `object.field_name`. So, for your example of getting client_order_id from Order objects, you would do `order.client_order_id`. You can see more examples at https://docs.alpaca.markets/api-documentation/how-to/.

**Comment by Jacyle** [comment]
> There are probably better ways out there, but this is the function that I wrote to handle. Super() objects are super annoying.
> 
> ```python
> def get_orders(status, start_date):
>     fetch_orders = api.list_orders(status=status, after=start_date)
>     orders = []
>     for i in range(fetch_orders.__len__()):
>         order = fetch_orders[i]._raw
>         orders.append(order)
>     return pd.DataFrame(orders)
> ```
This worked great! Thanks @tburkholder23
