### ISSUE TITLE
get_barset doesn't respect start and end date

### ISSUE THREAD

**Issue by ashkan-leo** [alpacahq/alpaca-trade-api-python#66]
The following code returns the data not in the provided time interval. It will return data for 2018 and 2019 while I set the end date to be 20150615.
```
api = tradeapi.REST(
    key_id='xxx',
    secret_key='xxx',
    base_url='https://paper-api.alpaca.markets'
)

api.get_barset(['AAPL', 'IBM'], timeframe='1D', end=pd.datetime(year=2015, month=6, day=15)).df.index.max()
```

**Comment by ttt733** [comment]
Hello, the issue is that timestamp parameters need to be formatted like this: `2019-04-30T09:30:00-04:00`. In our Python SDK, that means that for parameters like `end` you should do something like `pd.Timestamp('2015-6-15 09:30',tz='America/New_York').isoformat()`.
