### ISSUE TITLE
[Bug]:can't install alpaca-trade-api-python

### ISSUE THREAD

**Issue by chatofking** [alpacahq/alpaca-trade-api-python#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i try
pip3 install alpaca-trade-api
it shows
```
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
Failed to build aiohttp frozenlist multidict yarl
ERROR: Could not build wheels for aiohttp, frozenlist, multidict, yarl, which is required to install pyproject.toml-based projects 
```

### Expected Behavior

can install alpaca trade api python

### SDK Version I encountered this issue in

-

### Steps To Reproduce

```markdown
pip install alpaca-py
pip install pandas numpy scipy
pip3 install alpaca-trade-api
install https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by sshcli** [comment]
Try with Python 3.9 instead of 3.10
