### ISSUE TITLE
[Bug]: Fails to install with Python 3.11 due to `aiohttp==3.8.1` dependency

### ISSUE THREAD

**Issue by fumoboy007** [alpacahq/alpaca-trade-api-python#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Python 3.11, `pip install alpaca-trade-api~=2.0` fails with the following error for the `aiohttp` dependency:
```
aiohttp/_websocket.c:198:12: fatal error: 'longintrepr.h' file not found
  #include "longintrepr.h"
           ^~~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
----------------------------------------
ERROR: Failed building wheel for aiohttp
```

### Expected Behavior

`pip install alpaca-trade-api~=2.0` with Python 3.11 should succeed.

### SDK Version I encountered this issue in

2.3.0

### Steps To Reproduce

```markdown
1. Use Python 3.11.
2. Run `pip install alpaca-trade-api~=2.0`.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

This [issue](https://github.com/aio-libs/aiohttp/issues/6600) has already been fixed starting with `aiohttp` version 3.8.3. However, the `alpaca-trade-api` package [pins](https://github.com/alpacahq/alpaca-trade-api-python/blob/bf02b2b870de5c9961b867908698faed0c738abb/requirements/requirements.txt#L8) its `aiohttp` dependency to version 3.8.1. We should use a less restrictive requirement specification so that future `aiohttp` fixes are brought in automatically.

**Comment by datttran** [comment]
Is there any way I can install this with Python 3.11? I still have issue with aiohttp

**Comment by sshcli** [comment]
@datttran just move your code to the new official SDK `alpaca-py` 
`alpaca-py` is fully compatible with Python 3.11.

**Comment by alighten-dev** [comment]
alpaca-py is fully compatible with 3.11 but the New API is not included in alpaca-py it's only in the alpaca-trade-api which is not compatible with 3.11

**Comment by sshcli** [comment]
@alighten-dev  @datttran @fumoboy007  the `alpaca-trade-api` is no longer supported.

Just install `alpaca-py `and use the following code:

```
from alpaca.trading.client import TradingClient          # For trading api        
from alpaca.data import StockHistoricalDataClient       # For data 

api_key= 'xxxxxxxxxxxxxxxxxxxx'
api_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxx'
api = TradingClient(api_key, api_secret, paper=True)
data = StockHistoricalDataClient(api_key, api_secret )
```

**Comment by BaileySimrell** [comment]
Ok so @sshcli, it seems this definitely fixes the build/install-related issue, however when trying to run any of the example historical data scripts from Alpaca's docs, they all lead to an ominous 400 error in python 3.11, however after switching to 3.9 in my virtual environment, everything works perfectly.

**Comment by sshcli** [comment]
@BaileySimrell most of the docs and examples you will find out there are still making reference to the old sdk `alpaca-trade-api`
In terms of docs, this is the start point for the new sdk `alpaca-py`:
https://alpaca.markets/docs/python-sdk/api_reference/index.html

**Comment by BaileySimrell** [comment]
@sshcli yes, I have definitely realized that ... though the examples from the getting started alpaca-py reference you sent did not work on python 3.11 on my machine. after switching to 3.9, they all worked.

**Comment by sshcli** [comment]
@BaileySimrell if the error you are getting now if different from the original error posted in this issue (aiohttp error) I recommend you to create a new issue with all possible details and exact steps to reproduce it, in the new [alpaca-py](https://github.com/alpacahq/alpaca-py/issues) repo
