### ISSUE TITLE
No data with Polygon

### ISSUE THREAD

**Issue by TravelTrader** [alpacahq/alpaca-trade-api-python#68]
```
import alpaca_trade_api as tradeapi
api = tradeapi.REST(API_KEY, API_SECRET_KEY, API_URL)
data = api.polygon.historic_agg('minute', 'CYBR', limit=1000).df
```
Of course, I set the constants before. But it doesn't work. I get the following error:
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.polygon.io/v1/historic/agg/minute/CYBR?limit=1000&apiKey=XXXXXXXXX
```
Is there a possibility to solve that?
Maybe it's because I have no data subscription from Polygon? But how to get the data from IEX over Alpaca?
Thank you very much!

**Comment by tburkholder23** [comment]
If you funded your alpaca account then polygon access is included with your account. Provided this is the case, try just dropping whatever API_URL parameter that you're including in your connection setup. Below successfully returns successfully.

```Python
import alpaca_trade_api as tradeapi
api = tradeapi.REST(API_KEY, API_SECRET_KEY)
data = api.polygon.historic_agg('minute', 'CYBR', limit=1000).df
```

**Comment by ttt733** [comment]
The issue here is likely that you do not have a funded Alpaca brokerage account. If you do not, you will not be authorized to access the Polygon API. If you wish to, please link a bank account to your Alpaca account and deposit funds, then regenerate your keys and try again.

**Comment by daraul** [comment]
I can't have a funded alpaca account because I don't live in the states. Is there any way to switch to IEX?
