### ISSUE TITLE
Add support for Grouped Daily in polygon v2

### ISSUE THREAD

**Issue by tburkholder23** [alpacahq/alpaca-trade-api-python#69]
https://polygon.io/docs/#!/Stocks--Equities/get_v2_aggs_grouped_locale_locale_market_market_date

I forked and updated as a stop-gap, but would be great to include support for this in 'official' sdk since it reduces number of calls while building history.

**Comment by ttt733** [comment]
@tburkholder23 - as I was adding the v2 agg endpoint already, I went ahead and included it in this PR: https://github.com/alpacahq/alpaca-trade-api-python/pull/70

Feel free to review it if you like and see if it matches what you're looking for; I'll likely merge it over and release tomorrow.

**Comment by tburkholder23** [comment]
It's beautiful! Thanks for the quick turnaround, Trevor.
