### ISSUE TITLE
How do we submit an order?

### ISSUE THREAD

**Issue by fightthepower** [alpacahq/alpaca-trade-api-python#74]
I am kind of new to alpaca and algo trading itself. How do we submit an order in alpaca?

An example; its placing an after market hour trade by shorting one AAPL stock for an intraday trade.
```
api = tradeapi.REST(
    key_id='key',
    secret_key='secret',
    base_url='https://paper-api.alpaca.markets'
)
account = api.get_account()
print(account.status)

order=api.submit_order(
                symbol='AAPL',
                qty='1',
                side='sell',
                type='stop_limit',
                limit_price='176',
                stop_price='177',
                time_in_force='day',
            )
```

But I am getting this error
```
  raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: insufficient qty (0 < 1)

```

**Comment by umitanuki** [comment]
You should buy the stock first, before selling it. The error message says you don't have shares to sell.

**Comment by fightthepower** [comment]
Thank you for the reply and yes you are right about that. I was going through the docs and it seems alpaca doesn't  provide short selling for free accounts.
