### ISSUE TITLE
Missing market data

### ISSUE THREAD

**Issue by dambrogia** [alpacahq/alpaca-trade-api-python#81]
Hi, I have been a big fan of Alpaca so far and all it has to offer 😄 

I am grabbing market data for specific dates. It is inconsistently missing, even for very large, reputable and consistent assets such as GOOG. 

The following will return an empty dataframe: (2019-07-01 is a Monday)

    bars = alpaca_client_factory().get_barset(
        symbols=['GOOG'],
        start='2019-07-01T00:00:00-00:00',
        end='2019-07-02T00:00:00-00:00',
        timeframe='15Min',
    )
    
    print(bars.df)

Results:

    Empty DataFrame
    Columns: [(GOOG, open), (GOOG, high), (GOOG, low), (GOOG, close), (GOOG, volume)]
    Index: []

If I query for this same data in another iex data source I can see the data:
You'll need a token to run this (it's free).

    https://api.tiingo.com/iex/GOOG/prices?startDate=2019-07-01&endDate=2019-07-02&resampleFreq=15min&token=<use_a_free_token_from_tiingo>

This issue has nothing wrong with the python package (sorry for placing it in the repo, I wasn't sure where else to take this). I confirmed I can successfully retrieve market data for other start and end times.

For `2019-06-03T00:00:00-00:00` -- `2019-06-04T00:00:00-00:00`:

                                GOOG                                    
                                open      high      low     close volume
    time                                                                   
    2019-06-03 09:30:00-04:00  1065.010  1065.010  1040.50  1041.700  28399
    2019-06-03 09:45:00-04:00  1041.345  1041.785  1031.02  1032.480  18473
    2019-06-03 10:00:00-04:00  1031.505  1034.860  1030.30  1034.465  11078
    2019-06-03 10:15:00-04:00  1034.590  1041.410  1032.46  1040.340  13750
    2019-06-03 10:30:00-04:00  1040.705  1042.010  1034.91  1034.910   8126

## My questions are:
- Am I doing something wrong? Is this a user-error on my end?
- Is this expected? 
  - Is the iex data meant to show data for "all" stocks or just their [daily list](https://iextrading.com/account#/daily-list)? (will need an account to see that, also free)
- How stable is the market data endpoint considered to be?
- Why is the data missing? 
  - Is this expected?
  - Are there notifications for this? 
- Will the data be backfilled in the future? 
  - If so, what is the timeframe for backfilling missing data?

My intentions are just to find out what's going on so I can best handle this situation. Thanks for your help!

**Comment by bdowling** [comment]
@dambrogia appreciate the feedback.  We do have some gaps in our intraday data and unfortunately we cannot fill these gaps at this time.  We are working to try to improve the filling of this data going forward as well as looking for other sources we can use to populate this data.

If you have a funded account, polygon data is also available to you which is more comprehensive.
